### ISSUE TITLE
Speed up plugin build process in s2e-env

### ISSUE THREAD

**Issue by vitalych** [S2E/s2e-env#120]
``s2e build -r libs2e`` is too slow, it re-build too many unncessary things.
It's possible to use ``s2e build -r libs2e-release-make``, but it still rebuilds too many things (even if only one c++ file was changed)

**Comment by vitalych** [comment]
https://github.com/S2E/build-scripts/pull/17

**Comment by vitalych** [comment]
Could you please paste the command line you use for rebuilding + the output of the command?

**Comment by nihilscire** [comment]
I ran `s2e build -r libs2e`. The output is attached: [build.log](https://github.com/S2E/s2e-env/files/2026550/build.log)

**Comment by vitalych** [comment]
I see, yes that one will reconfigure libs2e and then rebuild everything. Did you try s2e build -r `libs2e-release-make` instead?

**Comment by nihilscire** [comment]
I rebuilt with `s2e build -r libs2e-release-make` and it took 1 minute. Thanks for the advice. 
Now I am wondering what's the difference between `s2e build -r libs2e` and `s2e build -r libs2e-release-make`?

**Comment by vitalych** [comment]
The S2E build process is split into components. libs2e will run the configure script, which will trigger a complete rebuild. libs2e-release-make just runs make. There is also libs2e-release-install that you may want to use as well.

**Comment by nihilscire** [comment]
Thanks for your help. I've just been working with plugins, so `libs2e-release-make` will do the job.
