### ISSUE TITLE
s2ecmd: allow making parts of files symbolic

### ISSUE THREAD

**Issue by vitalych** [S2E/s2e-env#129]
- Pass an argument/env var with a list of (offset, size)
- Test case would still have someone to capture the non-symbolic parts (maybe use s2eput).

**Comment by vitalych** [comment]
I must take this over. I have a 300KB ISO file to feed to cdfs.sys. Really need to make selective bytes symbolic.

**Comment by adrianherrera** [comment]
Sure, as you wish. I’m on holidays for he next 1.5 weeks, so I wouldn’t be
getting to it until I’m home anyway.

**Comment by adrianherrera** [comment]
Sure, as you wish. I’m travelling on holidays for the next 1.5 weeks, so I wouldn’t be getting to it until after that anyway.
