### ISSUE TITLE
Got problems when analysing unbreakable in GoogleCTF

### ISSUE THREAD

**Issue by beraphin** [S2E/s2e-env#138]
Hi
I wanna learn how to write s2e plugins so I searched it on Internet, then I saw the following link:
[Solving a CTF Challenge with S2E](https://adrianherrera.github.io/post/google-ctf-2016/
)and I did every steps in this artical, even found and copied code from 
[GoogleCTFUnbreakable.cpp](https://gist.github.com/adrianherrera/397dc68918374c81cf63e53e659bd083)
But after I built the plugin and ran launch.sh, it showed lots of output and never stop even after 1 or 2 hours, something like:
```
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false
projects/unbreakable/s2e-out-2/debug.txt:9 [State 0] BaseInstructions: Testing whether data at 0x403538 and size 1 is symbolic:  false

```
Then I added some codes in `GoogleCTFUnbreakable::onTranslateInstruction` in `GoogleCTFUnbreakable` to see the variable pc:
```
    if((pc&0xffffffffffff0000)==0x400000){
        count++;
        printf("%p\n",(void*)pc);
    }
```
then I got these stuff:
```
0x400920
0x400922
0x400925
0x400926
0x400929
0x40092d
0x40092e
0x40092f
0x400936
...
```
but they seems not to be the address in unbreakable：
![image](https://user-images.githubusercontent.com/25315905/40406080-d6890c5a-5e91-11e8-9cda-b1f4f30780a8.png)
 
So any suggestion?

**Comment by adrianherrera** [comment]
Hi @beraphin, I think you've accidentally hit enter before finishing your question 🙂

What is the question?

**Comment by adrianherrera** [comment]
Hmm weird that you're getting all those messages from BaseInstructions. I looked at 0x403538 and it appears to correspond to "Product activation failure %d\n" string.

Can you please show me your bootstrap.sh?

**Comment by beraphin** [comment]
`#!/bin/bash
#
# This file was automatically generated by s2e-env at 2018-05-22 07:47:21.002276
#
# This bootstrap file is used to control the execution of the Linux target
# program in S2E.
#
# When you run launch-s2e.sh, the guest VM calls s2eget to fetch and execute this
# bootstrap script. This bootstrap script and the S2E config file determine how
# the target program is analyzed.
#

sudo echo 0 > /proc/sys/kernel/randomize_va_space

set -x

# To save you the hassle of rebuilding the image every time you want to update
# S2E's guest tools, the first thing that we do is get the latest versions of
# the guest tools.
function update_guest_tools {
    local GUEST_TOOLS

    GUEST_TOOLS="$COMMON_TOOLS $(target_tools)"
    for TOOL in ${GUEST_TOOLS}; do
        ${S2EGET} guest-tools/${TOOL}
        chmod +x ${TOOL}
    done
}

function prepare_target {
    # Make sure that the target is executable
    chmod +x "$1"
}

# This prepares the symbolic file inputs.
# This function takes as input an optional seed file name.
# If the seed file is present, the commands makes the seed symbolic.
# Otherwise, it creates an empty file.
#
# Symbolic files must be stored in a ram disk, as only memory (and cpu)
# is capable of holding symbolic data.
#
# This function prints the path to the symbolic file on stdout.
function prepare_inputs {
    local SEED_FILE
    local SYMB_FILE

    # This can be empty if there are no seed files
    SEED_FILE="$1"

    SYMB_FILE="/tmp/input"


    if [ "x$SEED_FILE" = "x" ]; then
        # Create a symbolic file of size 256 bytes.
        # Note: you can customize this commands according to your needs.
        # You could, e.g., use non-zero input, different sizes, etc.

        truncate -s 256 ${SYMB_FILE}


        if [ $? -ne 0 ]; then
            ${S2ECMD} kill 1 "Failed to create symbolic file"
            exit 1
        fi
    else
        cp ${SEED_FILE} ${SYMB_FILE}
    fi

    # Make thie file symbolic
    ${S2ECMD} symbfile ${SYMB_FILE}
    echo ${SYMB_FILE}
}

# This function executes the target program given in arguments.
#
# There are two versions of this function:
#    - without seed support
#    - with seed support (-s argument when creating projects with s2e_env)
function execute {
    local TARGET
    local SEED_FILE

    TARGET=$1

    prepare_target "${TARGET}"


    execute_target "${TARGET}"

}

###############################################################################
# This section contains target-specific code

# This function executes the target program.
# You can customize it if your program needs special invocation,
# custom symbolic arguments, etc.
function execute_target {
    local TARGET
    TARGET="$1"




    # unbreakable is dynamically linked, so s2e.so has been preloaded to
    # provide symbolic arguments to the target if required. You can do so by
    # using the ``S2E_SYM_ARGS`` environment variable as required
    S2E_SYM_ARGS="1" LD_PRELOAD=./s2e.so ./${TARGET} CTF{xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx > /dev/null 2> /dev/null

}



# Nothing more to initialize on Linux
function target_init {
    # Start the LinuxMonitor kernel module
    sudo modprobe s2e
}

# Returns Linux-specific tools
function target_tools {
    echo "s2e.so"
}

S2ECMD=./s2ecmd
S2EGET=./s2eget
S2EPUT=./s2eput
COMMON_TOOLS="s2ecmd s2eget s2eput"

###############################################################################


update_guest_tools



# Don't print crashes in the syslog. This prevents unnecessary forking in the
# kernel
sudo sysctl -w debug.exception-trace=0

# Prevent core dumps from being created. This prevents unnecessary forking in
# the kernel
ulimit -c 0

# Ensure that /tmp is mounted in memory (if you built the image using s2e-env
# then this should already be the case. But better to be safe than sorry!)
if ! mount | grep "/tmp type tmpfs"; then
    sudo mount -t tmpfs -osize=10m tmpfs /tmp
fi

# Need to disable swap, otherwise there will be forced concretization if the
# system swaps out symbolic data to disk.
sudo swapoff -a



target_init

# Download the target file to analyze
${S2EGET} "unbreakable"



# Run the analysis
execute "./unbreakable"


# Kill states before exiting
${S2ECMD} kill $? "Target execution terminated"
`

**Comment by adrianherrera** [comment]
Can you please reformat it :)

**Comment by beraphin** [comment]
Sorry, what means "reformat"...I don't understand..

**Comment by adrianherrera** [comment]
No it's fine now; when you first uploaded it you got the Markdown wrong and it was hard to read. Hmm that looks fine to me! I haven't run this plugin in a while, so I'll have a look at it back in the office tomorrow.

Can you pleas upload the debug log to the Google group (https://groups.google.com/forum/#!forum/s2e-dev) Maybe there's something obvious lost in the logs...

**Comment by beraphin** [comment]
Ok, this is the link [Got problems when analysing unbreakable in GoogleCTF #138
](https://groups.google.com/forum/#!topic/s2e-dev/nmZv1L-9ncI)
Thank you anyway

**Comment by adrianherrera** [comment]
Thanks for that.

It does not look like you have enabled the necessary plugins to complete successfully. From my blog post:

```
At a minimum the following plugins must be enabled:

GoogleCTFUnbreakable
BaseInstructions
HostFiles
LinuxMonitor
ProcessExecutionDetector
```

I'd disable the searcher plugin and just use DFS.

Try this and let me know what happens.

**Comment by beraphin** [comment]
Oh my god it did work!

**Comment by adrianherrera** [comment]
Cool!

Are you sure you had the `GoogleCTFUnbreakable` plugin listed in the `s2e-config.lua` file? I cannot see a `Creating plugin GoogleCTFUnbreakable` message in the debug log that you posted.

**Comment by beraphin** [comment]
yeah I am sure. Maybe I post an old debug log for you T_T, I just noticed there are more than 20 debug logs in folder...

**Comment by vitalych** [comment]
Re. CUPA searcher, it would be nice to look at your logs. I noticed recently that in some configurations it switches states too frequently, slowing things down. You could add "batch" class to the CUPASearcher config so that it keeps a state run longer, like this:

```
pluginsConfig.CUPASearcher = {
    -- The order of classes is important, please refer to the plugin
    -- source code and documentation for details on how CUPA works.
    classes = {
        "batch", --Either first, or right after "seed" class, if present.
        "pagedir",
        "pc",
    },
    logLevel="debug",
    enabled = true
}

**Comment by beraphin** [comment]
Ok, now even if I add searcher in s2e-config.lua (without "batch"), it gives me flag very soon.
Strange...
Anyway, thanks a lot

**Comment by adrianherrera** [comment]
No problems! Unless there is anything else, I'm going to close this issue.
