### ISSUE TITLE
Add support for symbolic MMX registers

### ISSUE THREAD

**Issue by humeafo** [S2E/s2e-env#144]
KLEE: WARNING: silently concretizing (instruction: tcg-llvm-insttb-62-8048788:   call void @helper_fucomi_ST0_FT0()) (reason: access to cc_src register from libcpu helper) expression (Or w32 (Or w32 (And w32 (LShr w32 N0:(And w32 N1:(Or w32 (Xor w32 0x3344dead

On debian 9 x86_64 such silently concretizing even occur(in os/library code?) even before the real code had a chance to run:

KLEE: WARNING: silently concretizing (instruction: tcg-llvm-tb-7faccfc67ea7-11-444-0-40c2b7:   store i64 %9, i64* %11) (reason: write to always concrete memory name:ConcreteCpuRegisters offset=0x1f8 value=(Or w64 (Shl w64 (Concat w64 (Extract w8 24 N0:(Extract w32 0 (Or w64 (Shl w64 (Concat w64 (Extract w8 24 N1:(Extract w32 0 (Or w64 (Shl w64 (ReadLSB w64 0x14 

It seems others encountered such silently concretizing too: https://github.com/S2E/libcpu/issues/5, considering MMX float registers etc appears more common in modern software with compilers default  targeting such instruction set and the difficulties to correctly implement this, I think official support for this would be really great.

**Comment by vitalych** [comment]
Yep, supporting this would be awesome. We welcome contributions :)

**Comment by humeafo** [comment]
I'll give it a try, but may fail...^~^

**Comment by humeafo** [comment]
@vitalych I did a fast prototype:
move mmx and fp regs to sym region in CPUState, then wrapped all MMX and FP access in wrappers in op_helpers.c and helpers.c, compile softfloat.c and linked it into op_helper.bc, but it didn't work as expected(no crash, tests results not correct), Is there anything I missed or was wrong? 

you said: "There may be tweaks required in tcg-llvm.cpp to accomodate for extra symbolic registers."  what did exactly this mean?

Any advice on debugging such issues?

**Comment by vitalych** [comment]
That's awesome progress, I think the bulk of the work is done, now comes the hard part of debugging :)
tcg-llvm has some assumptions about the locations of registers in cpustate, like here: https://github.com/S2E/libtcg/blob/master/src/tcg-llvm.cpp#L692, but that's just a random idea. You should use a debugger.

To debug this, I suggest that you take the test BIOS from here: https://github.com/S2E/guest-tools/tree/master/s2ebios, and add a couple MMX instructions for debugging. You can then set a break point and follow all the chain from translation down to execution.

The idea is that the bios is very small and doesn't have any OS interference, this makes it suitable for debugging the exection engine.

**Comment by vitalych** [comment]
Also, could you send a pull request (even if preliminary)? I'd be happy to take a look.

**Comment by humeafo** [comment]
@vitalych I totally ignored this, maybe this is the place where things went wrong, I think this part of code maybe more portable if using the llvm::StructLayout to auto reason about the gep index instead of hardcoding. I'll open a PR for the basic wrappers I prototyped for now, no debugging done yet, just compiled.

**Comment by humeafo** [comment]
A experiment PR is opened for you to review what's been going wrong.

**Comment by vitalych** [comment]
I've looked through it, looks like a massive amount of work! I'd be curious to know if you automated the conversions to some extent. In any case, we'll have to stress test this with a testsuite, code review is very hard because 99.9% of the code is very similar and you'd just scroll through it. So here are some tips:

- Find an MMX/FP-intensive benchmark that has consistency checks in it
- First check that concrete execution works properly ({i386|x86_64}-softmmu builds).
- Then move to symbolic execution
- It would be nice to have a build of S2E with gcov enabled, just to make sure that no function has been missed.

**Comment by humeafo** [comment]
Thanks for your advice! 
This is done semi-automated with some scripts and some manual effort. Now it seems tcg-llvm.cpp obviously need some tweaking before going any further.

**Comment by vitalych** [comment]
I've just realized that the KLEE version that we have does not support floating point expressions, you might run into this problem. You might need to take some functionality from https://github.com/srg-imperial/klee-float.

**Comment by humeafo** [comment]
@vitalych After reading the codes, I found qemu's floating point was implemented in softfloat.c which use scalar arithemetic to simulate floating point,  If I was not wrong then no need to support  floating point expressions in klee, the existing bv support should be enough to support floating point SE in S2E. But the cost may be the solver's side would see much complex and hard to solve constraints compared to native floating constraints support, another problem may be the forking of states in softfloat helpers may cause many floating point problems not solvable.

**Comment by vitalych** [comment]
@humeafo any news on MMX support?

**Comment by humeafo** [comment]
@vitalych sorry for the late response because of some other project matters. Basically mmx and floating point support seems worked, but because of some other affairs, I didn't have enough time to test it further.
The fp support will fork in internal helper codes, which made path explosion a problem, but it seems work correctly.

**Comment by vitalych** [comment]
@humeafo  no worries, feel free to send pull requests for what you have so far.
Re. tests, we'll come up with a testing infrastructure soon, so it should help validating.
Re. FPs, I wonder if we could switch to native FP and use KLEE/Z3 to reason about it instead of emulating FP with integers.

**Comment by humeafo** [comment]
Native FP support would require much more work. I'd squeeze some time to send PR. I noticed some previous related PR still pending, I'll see what's needed to be done for these first.

**Comment by clevcode** [comment]
I would love to see, and try out, a pull request for this issue, even if it's not ready to be merged to master yet. It is quite important, since MMX registers are commonly used in optimized string/buffer handling routines, which leads to my symbolic inputs being concretized.

**Comment by vitalych** [comment]
@humeafo any chance you could push anything you have? Even if it's very rough code, it would be very useful. I'd be happy to take over, clean it up and test if you don't have time. I am starting to get personally impacted by the lack of MMX support and would rather avoid having to duplicate your work.

**Comment by humeafo** [comment]
@vitalych sorry for the late response for some work matters, I'll push the codes after I got a test env, it should work in my experiments, but of course some more testing is needed.

**Comment by vitalych** [comment]
@humeafo thanks, no need for testing, you can just dump whatever you have now. I hope you are not prevented from releasing it because of some administrative reason. Releasing it would be of tremendous help to everyone on the forum who keeps bumping in concretization issues.

**Comment by humeafo** [comment]
@vitalych I just did a merge of my old version to master, I even didn't try to compile it, no clang-format etc, hope you can take over it and added it into S2E. Another patch to libtcg is needed, I'd open another PR.

**Comment by humeafo** [comment]
The libtcg patch done, I didn't compile it either, hope it compile as libtcg is not modified for years, format and naming etc is not done carefully, so you can take over of that too.

**Comment by vitalych** [comment]
This is amazing! I'll try it out asap.

**Comment by vitalych** [comment]
Almost one year after this issue was opened, symbolic MMX/XMM/FP register support is ready!
Here are PRs, sorted by complexity.

Various fixes that came up while debugging MMX support:
https://github.com/S2E/guest-images/pull/26
https://github.com/S2E/testsuite/pull/6
https://github.com/S2E/s2e-env/pull/296
https://github.com/S2E/klee/pull/14
https://github.com/S2E/guest-tools/pull/37
https://github.com/S2E/libs2eplugins/pull/56

MMX support itself:
https://github.com/S2E/libs2ecore/pull/21
https://github.com/S2E/libtcg/pull/3
https://github.com/S2E/libcpu/pull/19

**Comment by humeafo** [comment]
I'm glad that MMX/FP support finally works, obviously I missed some places for not so familiar with the internals of S2E， thanks for your great work!
