### ISSUE TITLE
cc_tmp accesses in CPUState are not wrapped

### ISSUE THREAD

**Issue by humeafo** [S2E/s2e-env#151]
cc_tmp is placed in symbolic region, but I found no wrapper is used to access cc_tmp in codebase, cc_src is replaced with CC_SRC etc, why cc_tmp is so special or just a bug?

**Comment by vitalych** [comment]
That's a very good point, probably a bug. I can't think of any reason why it shouldn't be wrapped.
cc_tmp is not used very much so perhaps that's why it went unnoticed. There may be problems if symbolic code has rotation instructions in them. Please try and let us know!
