### ISSUE TITLE
How to disable ASLR in qemu?

### ISSUE THREAD

**Issue by beraphin** [S2E/s2e-env#164]
I want to analysis binary with pie using s2e, and first I want to disable ASLR to make sure the addresses are the same when it is running in s2e every time. So I added following codes in bootstrap.sh:
 ```
    sudo echo 0 >/proc/sys/kernel/randomize_va_space
    cat /proc/sys/kernel/randomize_va_space > ./record
    cat input |S2E_SYM_ARGS="" LD_PRELOAD=./s2e.so ./${TARGET}  > /dev/null 2> /dev/null
```
However, the address were not the same every time I running s2e, and the content of `/s2e-last/outfiles/0/record` is still 2 (I used `s2eput` to pull `record `from qemu to host)
Then I realized that I cannot disable ASLR just like
`sudo echo 0 >/proc/sys/kernel/randomize_va_space`
I must switch to root first, like:
```
su
echo 0 >/proc/sys/kernel/randomize_va_space
```
It seems not easy to switch to root in bash script, so I think if there is a way to upload file from host to qemu to overwrite `randomize_va_space`.
As far as I know the only way is to use `s2eget` command, but this command is running inside qemu, too. So it is limited by user permission.

So I am wondering if there is an easy way to disable ASLR in qemu?
Thx.

**Comment by vitalych** [comment]
Problem is input redirection, it is done by the shell, not by sudo. You need to rewrite your command with ``tee```.

**Comment by beraphin** [comment]
Thanks a lot, my problem was solved perfectly!
