### ISSUE TITLE
s2e image_build linux gets stuck

### ISSUE THREAD

**Issue by humeafo** [S2E/s2e-env#169]
When building the newest images,:
s2e image_build linux

stuck after shown the following message:

Using default distribution of 'unstable' in the changelog
Install lsb-release or set $KDEB_CHANGELOG_DIST explicitly
dpkg-deb: building package 'linux-headers-4.9.3-s2e' in '../linux-headers-4.9.3-s2e_4.9.3-s2e-3_i386.deb'.
dpkg-deb: building package 'linux-libc-dev' in '../linux-libc-dev_4.9.3-s2e-3_i386.deb'.
dpkg-deb: building package 'linux-image-4.9.3-s2e' in '../linux-image-4.9.3-s2e_4.9.3-s2e-3_i386.deb'.
dpkg-deb: building package 'linux-image-4.9.3-s2e-dbg' in '../linux-image-4.9.3-s2e-dbg_4.9.3-s2e-3_i386.deb'.
dpkg-source: info: using source format '3.0 (custom)'
dpkg-source: info: building linux-4.9.3-s2e in linux-4.9.3-s2e_4.9.3-s2e-3.dsc
dpkg-genchanges: info: including full source code in upload

After this, seems the build process stuck forever...

**Comment by humeafo** [comment]
Separately run the following command seems result in the same situation as described above.
/home/user/mdev/symexec/s2e/s2e2/source/guest-images//Linux/docker/run-docker.sh linux-build-i386 /home/user/mdev/symexec/s2e/s2e2/images/.tmp-output/linux-4.9.3-i386/linux-4.9.3 /home/user/mdev/symexec/s2e/s2e2/source/guest-images//Linux/docker/make-kernel.sh /home/user/mdev/symexec/s2e/s2e2/source/s2e-linux-kernel/include 1000 1000

**Comment by vitalych** [comment]
It would help to have more details, at least what is getting stuck. Is there any CPU or I/O activity, is QEMU running, etc...

**Comment by humeafo** [comment]
No qemu, no diskio, no cpu, only some run_docker.sh and many docker run -rm -i ... process, I can hit this on ubuntu 16 on two machines, maybe you can repo this if start a fresh build...

**Comment by vitalych** [comment]
Which  ``docker run -rm -i ...``? the omitted ... could be useful.
Could you dump the processes running inside docker when it gets stuck?

**Comment by humeafo** [comment]
Thank you for the help, after some investigation, seems this is caused by some docker image corruption, after cleanup and rebuild, seems ok now,
