### ISSUE TITLE
Problems about state fork

### ISSUE THREAD

**Issue by beraphin** [S2E/s2e-env#171]
Hello again,
I wanna trace a sequence of basic blocks to collect constraints without a concrete input. So I make the symbolic input by running s2e as `./s2ecmd symbwrite 1000 | ${TARGET}`
But in some branch points s2e didn't fork any state and just ran to unexpected path, and in some branch point it fork infinit states.
No matter if I enable concolic mode or not, the results were the same.
Any suggestions about this problem?
Thanks

**Comment by vitalych** [comment]
Hi. Could you send the program that causes issue? It's too vague otherwise.
In general, when you have path explosion, starts with fewer symbolic inputs (1, 2, 8, etc.). 1000 looks too big.

Also, unless it is a bug or feature request, it's better to use the s2e-dev forum instead. Thanks.
