### ISSUE TITLE
s2e-env: allow running s2e.py in any subdirectory of the environment

### ISSUE THREAD

**Issue by vitalych** [S2E/s2e-env#180]
At the moment, you have to be at the root of the env.
Commands like `s2e forkprofiler` should be available in the project folder as well (and autodetect the project name so that one does not have to type it).

**Comment by adrianherrera** [comment]
This isn’t true anymore. There is an activate script in `install/bin`, just
like a python virtualenv.

**Comment by vitalych** [comment]
nice, didn't know about that.
