### ISSUE TITLE
s2e run prevented env var from being passed to s2e instance

### ISSUE THREAD

**Issue by humeafo** [S2E/s2e-env#190]
This indeed may prevent some flexible usage by using env var, Is this intended for some reason or a bug?

**Comment by vitalych** [comment]
Could you elaborate more? Which env vars?

**Comment by humeafo** [comment]
Eg, some plugin want to used a env var ENVAR_A, but run the  following command:
ENVAR_A=VALUEA s2e run myproject 
the plugin won't see ENVAR_A.

**Comment by vitalych** [comment]
Indeed, this sets a clean env:
https://github.com/S2E/s2e-env/blob/master/s2e_env/commands/run.py#L271

Perhaps you could inherit the original too.
