### ISSUE TITLE
Current refactored bootstrap.sh can't generate correct SYMB_FILE name

### ISSUE THREAD

**Issue by humeafo** [S2E/s2e-env#191]
The problem is that ${S2EGET} ${SEED_FILE}.symranges will output "Waiting for S2E mode..." at
https://github.com/S2E/s2e-env/blob/master/s2e_env/templates/bootstrap.sh#L98

then the SYMB_FILE="$(prepare_inputs ${SEED_FILE})" at https://github.com/S2E/s2e-env/blob/master/s2e_env/templates/bootstrap.sh#L154 will got "Waiting for S2E mode...\n"+"${REAL_SYMB_FILE_NAME}" which is obviously won't work.

**Comment by vitalych** [comment]
I don't understand the problem. Is this in single path mode? s2eget should work the same there. The message you see will only happen if you run a non-s2e build of libs2e.

**Comment by humeafo** [comment]
The problem exists seems after your last commit, if you use seed now at runtime SYMB_FILE will get value "Waiting for S2E mode...\nXXXXXXX" so the seeds mode won't work now.

**Comment by vitalych** [comment]
ok, now I get it, thanks. I didn't realize that there would be the waiting for s2e mode message. I suppose a fix would be to redirect s2eget output to /dev/null. Please send a fix.
