### ISSUE TITLE
Upgrade LLVM

### ISSUE THREAD

**Issue by adrianherrera** [S2E/s2e-env#201]
LLVM 3.9.1 is getting pretty old now. Upgrade to a newer version of LLVM.

**Comment by vitalych** [comment]
Started working on it to see if #294 disappears. Unfortunately, there are quite substantial changes to KLEE as well that we'd have to pull.

**Comment by vitalych** [comment]
We have LLVM 13 now, so it's time to upgrade again, together with new support for Ubuntu 22.04 LTS
