### ISSUE TITLE
QEMU error building a image

### ISSUE THREAD

**Issue by caballomaldito** [S2E/s2e-env#208]
SO: Ubuntu 18.04 TLS under VMWare Workstation

Execute the following command to reproduce the problem:

s2e image_build debian-9.2.1-x86_64

Result:

**qemu-system-x86_64: error: failed to set MSR 0x38d to 0x0
qemu-system-x86_64: /build/qemu-11gcu0/qemu-2.11+dfsg/target/i386/kvm.c:1807: kvm_put_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.**
libguestfs: error: appliance closed the connection unexpectedly, see earlier error messages
libguestfs: child_cleanup: 0x555b00cce0d0: child process died
libguestfs: sending SIGTERM to process 53245
libguestfs: error: /usr/bin/qemu-system-x86_64 killed by signal 6 (Aborted), see debug messages above
libguestfs: error: guestfs_launch failed, see earlier error messages
libguestfs: trace: launch = -1 (error)
libguestfs: trace: close
libguestfs: closing guestfs handle 0x555b00cce0d0 (state 0)
libguestfs: command: run: rm
libguestfs: command: run: \ -rf /tmp/libguestfs97F4IH
libguestfs: command: run: rm
libguestfs: command: run: \ -rf /run/user/1000/libguestfsYmLEZJ

Expected result:

Image built

Any ideas?, Thank you!

**Comment by vitalych** [comment]
This is strange, it looks like it is using system qemu instead of the one that comes with S2E.

**Comment by vitalych** [comment]
Looks like a problem with your system's QEMU version. Make sure that it is properly setup. In particular, check that libguestfs works (try to copy some files from/to disk images using virt-copy-* commands).

**Comment by caballomaldito** [comment]
Solved

Thank you!
