### ISSUE TITLE
Seeds files are not fetched

### ISSUE THREAD

**Issue by caballomaldito** [S2E/s2e-env#209]
s2e new_project --use-seeds --enable-pov-generation --image debian-9.2.1-x86_64 /home/peto/Desktop/myapp @@ /dev/null

cd /home/peto/s2e/projects/myapp && ./launch-s2e.sh

SeedScheduler: explorationState: 2 timeOfLastFetchedSeed: 460 foundBlocks: 439s foundCrashes: 460s hpSeed: 460s
SeedScheduler: idle detection: single instance
SeedSearcher: idle setting: idx=0 idle=1
SeedSearcher: Looking for new seeds
**SeedSearcher: /home/peto/s2e/projects/myapp/seeds/1.png is not a valid seed name**
**SeedSearcher: Fetched 0 valid seeds**

I have put 20 seeds into the folder /home/peto/s2e/projects/myapp/seeds/

My questions are, 

1. Why 0 seeds are fetched?
2. How can i see the progress of the project running?

Thank you!

**Comment by vitalych** [comment]
As mentioned in the message, the name of the seed is invalid. Please refer to the documentation on proper nameing.
