### ISSUE TITLE
s2e image_build fails in qemu boot

### ISSUE THREAD

**Issue by Da5hes** [S2E/s2e-env#214]
when i try to build the images on ubuntu 18 i encounter the following error:

>s2e image_build linux --gui
>INFO: [image_build] The following images will be built:
>INFO: [image_build]  * debian-9.2.1-i386
>INFO: [image_build]  * debian-9.2.1-x86_64
>INFO: [image_build]  * cgc_debian-9.2.1-i386
>INFO: [image_build] Kernel repository already exists in /home/da5h/s2e/source/s2e-linux-kernel
>make: Entering directory '/home/da5h/s2e/images'
>[Thu Nov  1 11:26:01 IST 2018] [/home/da5h/s2e/images/debian-9.2.1-x86_64/image.raw.s2e.ready] Creating snapshot...
>[Thu Nov  1 11:26:01 IST 2018] [/home/da5h/s2e/images/debian-9.2.1-i386/image.raw.s2e.ready] Creating snapshot...
>LD_PRELOAD=/home/da5h/s2e/install/share/libs2e/libs2e-x86_64.so /home/da5h/s2e/install/bin/qemu-system-x86_64 -enable-kvm -drive if=ide,index=0,file=/home/da5h/s2e/images/debian-9.2.1-x86_64/image.raw.s2e,format=s2e,cache=writeback -serial file:/home/da5h/s2e/images/debian-9.2.1-x86_64/serial_ready.txt -enable-serial-commands -net none -net nic,model=e1000  -m 256M 
LD_PRELOAD=/home/da5h/s2e/install/share/libs2e/libs2e-i386.so /home/da5h/s2e/install/bin/qemu-system-i386 -enable-kvm -drive if=ide,index=0,file=/home/da5h/s2e/images/debian-9.2.1-i386/image.raw.s2e,format=s2e,cache=writeback -serial file:/home/da5h/s2e/images/debian-9.2.1-i386/serial_ready.txt -enable-serial-commands -net none -net nic,model=e1000  -m 256M 
>Starting libs2e...
>Opening /dev/kvm
>Warning: vlan 0 is not connected to host network
>Starting libs2e...
>Opening /dev/kvm
>Warning: vlan 0 is not connected to host network

in qemui see that ipxe is getting a timeout after which there is obviously no bootable device

**Comment by vitalych** [comment]
Hi,

Perhaps there are left overs from a previously interrupted build, so it tries to create a snapshot from a partially built base image, which then fails. Please remove all files in `/home/da5h/s2e/images/*debian-*` and try again.

**Comment by Da5hes** [comment]
indeed that was the problem, thanks!
