### ISSUE TITLE
revgen: upgrade to mcsema2

### ISSUE THREAD

**Issue by vitalych** [S2E/s2e-env#225]
Revgen currently uses a very old mcsema cfg recovery script. It needs upgrading:

- Checkout https://github.com/trailofbits/mcsema
- Build the python/C protobufcfg
- Install the python scripts so that s2e-env can find them

**Comment by Pl0414141** [comment]
Vitalych,

can you explain with more details the steps of how to do the work?. I have free time and i would like to do it.

**Comment by vitalych** [comment]
First, go through the revgen tutorial to understand every step in the translation process.
You will have to upgrade these two files. They extract the CFG so that revgen can parse it. They come from a very old version of mcsema. I don't remember the details anymore.
- https://github.com/S2E/s2e/blob/master/tools/lib/Utils/cfg.proto
- https://github.com/S2E/s2e/blob/master/tools/tools/scripts/ida/mcsema_get_cfg.py

**Comment by vitalych** [comment]
Revgen has been removed.
