### ISSUE TITLE
Signal emitting does not work correctly

### ISSUE THREAD

**Issue by Epeius** [S2E/s2e-env#242]
Hi,
In https://github.com/S2E/libfsigcxx/blob/master/include/fsigc%2B%2B/fsigc%2B%2B.h#L240,
```
void emit(PARAM_TYPES... params) {
        for (auto &it : m_funcs) {
            it.first->operator()(params...);
        }
}
```  
Once an `operator` is disconnected (i.e., erased from `m_funcs`) in this loop, `it` iterator may not work properly.

Maybe we can change to the following code?
```
void emit(PARAM_TYPES... params) {
        auto tmp_funcs = m_funcs;
        for (auto &it : tmp_funcs) {
            it.first->operator()(params...);
        }
}
```

-Bin

**Comment by vitalych** [comment]
@Epeius please check the fix

**Comment by Epeius** [comment]
Sure!
