### ISSUE TITLE
pip --process-dependency-links "no such option"

### ISSUE THREAD

**Issue by courtwebs** [S2E/s2e-env#245]
It looks like with pip 19, `--process-dependency-links` no longer exists. See the following:

```
$ pip install --process-dependency-links .

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --process-dependency-links
```

I worked around this by forcing my virtualenv to use pip 18.1:

```
$ pip install pip==18.1
```

Just thought I'd open an issue so you folks are aware that current installation instructions for s2e-env don't work with pip 19.

**Comment by vitalych** [comment]
Thanks! I hope they have an alternative to this option now.

**Comment by adrianherrera** [comment]
Doesn't really look like it 😐

**Comment by vitalych** [comment]
Please try https://github.com/S2E/s2e-env/pull/247

**Comment by vitalych** [comment]
It just breaks on very old pip versions, which ignores the custom URL in setup.py. This is a problem for anyone who installs S2E system wide on Ubuntu 16 (e.g., the docker images).
