### ISSUE TITLE
Build issue when linking CXX executable s2ecmd

### ISSUE THREAD

**Issue by jessebartels** [S2E/s2e-env#251]
Hey folks,

I've followed the build process for s2e successfully up until the point I run s2e build. At this point, the linker throws a bunch of linking errors, i.e.:

_undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned int&, unsigned int)'_ 

or

 _undefined reference to `VTT for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >'_

Followed by 

clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
common/s2ecmd/CMakeFiles/s2ecmd.dir/build.make:120: recipe for target 'common/s2ecmd/s2ecmd' failed
make[3]: *** [common/s2ecmd/s2ecmd] Error 1
make[3]: Leaving directory '/scratch/new_lhome/jessebartels/buildS2E/build/s2e/guest-tools32'
CMakeFiles/Makefile2:282: recipe for target 'common/s2ecmd/CMakeFiles/s2ecmd.dir/all' failed
make[2]: *** [common/s2ecmd/CMakeFiles/s2ecmd.dir/all] Error 2
make[2]: Leaving directory '/scratch/new_lhome/jessebartels/buildS2E/build/s2e/guest-tools32'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/scratch/new_lhome/jessebartels/buildS2E/build/s2e/guest-tools32'
/scratch/new_lhome/jessebartels/buildS2E/source/s2e/Makefile:166: recipe for target 'stamps/guest-tools32-make' failed

I was wondering if you folks have any recommendations for getting s2e to build. I appreciate your time and patience, thank you

**Comment by vitalych** [comment]
Hi! On what OS are you building it? Maybe you are missing packages, though it's unlikely. If in doubt, have a look at the S2E docker images.

**Comment by jessebartels** [comment]
I am building on Ubuntu 16.04.5. I tried manually installing all of the dependencies listed under "[Building S2E Manually](http://s2e.systems/docs/BuildingS2E.html)" and it seems that everything is up to date.

**Comment by vitalych** [comment]
Maybe it has missing dependencies. The docker file is the gold standard, you can pull references from there.
https://github.com/S2E/build-scripts/blob/master/Dockerfile

**Comment by jessebartels** [comment]
Aye, I've pulled all of the dependencies listed there and it seems that everything should be up to date. It seems that other [folks](https://stackoverflow.com/questions/33394934/converting-std-cxx11string-to-stdstring) have had build issues like this and it has to do with different versions of gcc. Do you know if there is a required version of gcc for building S2E??

**Comment by vitalych** [comment]
S2E uses clang to build itself, which it compiles from source.
Can you go to the `build/s2e/guest-tools32` folder and run make manually there? Do you have the same issue with `build/s2e/guest-tools64`? If no, then it must be an issue with 32-bit libraries.

**Comment by jessebartels** [comment]
Running make manually in guest-tools32 brings up the same linking issues. Unfortunately, there doesn't yet seem to be a guest-tools64 folder (i.e. the build process dies before getting through guest-tools32). I tried looking through the --rebuild-components command, but that only lists "guests", which starts from guest-tools32. Do you know of anyway to skip building the 32 bit version of guest tools?

**Comment by vitalych** [comment]
In your `build/s2e` folder, run `make -f /path/to/Makefile stamps/guest-tools64-make`.
You can build other targets the same way, just look for them in here:
https://github.com/S2E/build-scripts/blob/master/Makefile#L731

**Comment by jessebartels** [comment]
Aye, looks like the 64 bit versions work! Thank you very much (I shouldn't need to work with any 32 bit executables). I appreciate the assistance, if you want I can keep poking the 32 bit versions of guest tools but otherwise I should be able to proceed with S2E. Thank you!

**Comment by vitalych** [comment]
Closing for now as there is no more info for debugging
