### ISSUE TITLE
guest-images: check libguestfs version for buggy ones

### ISSUE THREAD

**Issue by MRLEE123456** [S2E/s2e-env#261]
I spent a lot of time using imege_build and still didn't generate an image.raw.s2e.  In [/ home/s2e/s2e/guest - images/output/cgc_debian - 9.2.1 - i386 / image. Raw. The s2e] Installing kernels...It took five hours and it continues.

**Comment by vitalych** [comment]
Hi, could you please attach the output of the build process? That will tell us where it got stuck. Alternatively, you can download pre-built images (-d option).

**Comment by MRLEE123456** [comment]
Thank you for your answer! 
The following code is where I've been stuck
```
[Sun Mar  3 17:54:33 PST 2019] [/home/s2e/s2e/guest-images/output/cgc_debian-9.2.1-i386/image.raw.s2e] Installing kernels...
Reaping winning child 0x562e86f00e00 PID 121761 
LIBGUESTFS_HV=/home/s2e/s2e/guest-images//qemu.wrapper virt-copy-in -a "/home/s2e/s2e/guest-images/output/cgc_debian-9.2.1-i386/image.raw.s2e" /home/s2e/s2e/guest-images/.tmp-output/decree-cgc-cfe-i386/*.deb /home/s2e
Live child 0x562e86f00e00 (/home/s2e/s2e/guest-images/output/cgc_debian-9.2.1-i386/image.raw.s2e) PID 121768 
Live child 0x562e86efa360 (/home/s2e/s2e/guest-images/output/debian-9.2.1-x86_64/image.raw.s2e) PID 121766 
Live child 0x562e86ee3f10 (/home/s2e/s2e/guest-images/output/debian-9.2.1-i386/image.raw.s2e) PID 121767

```

**Comment by vitalych** [comment]
Looks like a problem with your libguestfs. If you use vanilla Ubuntu 18, their libguestfs is buggy, you must update it manually (with apt-get update).

**Comment by MRLEE123456** [comment]
Thank you for helping me solve the problem.
