### ISSUE TITLE
Can add an installation source

### ISSUE THREAD

**Issue by MRLEE123456** [S2E/s2e-env#262]
Hi,I am in mainland China, due to the firewall of the government, I cannot use s2e-env to install s2e platform and set up image.So I am asking for your help to add an installation source so that s2e-env can download the required source files through GitHub.

**Comment by vitalych** [comment]
Hi, I created two specific issues which should solve your problem. They are pretty low on our priority list though, so you might want to use a VPN in the meantime (or take a stab at them).

https://github.com/S2E/s2e-env/issues/265
https://github.com/S2E/s2e-env/issues/264
