### ISSUE TITLE
s2e build error seems missing dependencies

### ISSUE THREAD

**Issue by FlyRabbit** [S2E/s2e-env#272]
I wrote my plugin and wanted to build it.
I run `s2e build -r libs2e`, something wrong

> make[3]: Leaving directory '/home/etenal/s2e/build/s2e/llvm-release'
In file included from /home/etenal/s2e/build/s2e/llvm-3.9.1.src/tools/gold/gold-plugin.cpp:15:
In file included from /home/etenal/s2e/build/s2e/llvm-3.9.1.src/include/llvm/ADT/StringSet.h:17:
In file included from /home/etenal/s2e/build/s2e/llvm-3.9.1.src/include/llvm/ADT/StringMap.h:17:
In file included from /home/etenal/s2e/build/s2e/llvm-3.9.1.src/include/llvm/ADT/StringRef.h:13:
/home/etenal/s2e/build/s2e/llvm-3.9.1.src/include/llvm/ADT/iterator_range.h:22:10: fatal error: 'utility' file not found
#include \<utility\>

I tried to rebuild `libs2e` serval times, and this is the first time I encountered this problem.
So I create another folder and initialize s2e again.
`s2e init`
`s2e build`

Also error

> =Release /home/etenal/s2e_test/build/s2e/llvm-3.9.1.src
-- The C compiler identification is Clang 3.9.1
-- The CXX compiler identification is Clang 3.9.1
-- The ASM compiler identification is Clang
-- Found assembler: /home/etenal/s2e_test/install/bin/clang
-- Check for working C compiler: /home/etenal/s2e_test/install/bin/clang
-- Check for working C compiler: /home/etenal/s2e_test/install/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/etenal/s2e_test/install/bin/clang++
-- Check for working CXX compiler: /home/etenal/s2e_test/install/bin/clang++ -- broken
**CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:45** (message):
  The C++ compiler
    "/home/etenal/s2e_test/install/bin/clang++"
  is not able to compile a simple test program.
  It fails with the following output:
    **Change Dir: /home/etenal/s2e_test/build/s2e/llvm-release/CMakeFiles/CMakeTmp
    Run Build Command:"/usr/bin/make" "cmTC_93503/fast"
    make[1]: Entering directory '/home/etenal/s2e_test/build/s2e/llvm-release/CMakeFiles/CMakeTmp'
    /usr/bin/make -f CMakeFiles/cmTC_93503.dir/build.make CMakeFiles/cmTC_93503.dir/build
    make[2]: Entering directory '/home/etenal/s2e_test/build/s2e/llvm-release/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_93503.dir/testCXXCompiler.cxx.o
    /home/etenal/s2e_test/install/bin/clang++    -march=x86-64    -o CMakeFiles/cmTC_93503.dir/testCXXCompiler.cxx.o -c /home/etenal/s2e_test/build/s2e/llvm-release/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    Linking CXX executable cmTC_93503
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_93503.dir/link.txt --verbose=1
    /home/etenal/s2e_test/install/bin/clang++  -march=x86-64     CMakeFiles/cmTC_93503.dir/testCXXCompiler.cxx.o  -o cmTC_93503 
    /usr/bin/ld: cannot find -lstdc++
    clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
    CMakeFiles/cmTC_93503.dir/build.make:97: recipe for target 'cmTC_93503' failed
    make[2]: *** [cmTC_93503] Error 1
    make[2]: Leaving directory '/home/etenal/s2e_test/build/s2e/llvm-release/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_93503/fast' failed
    make[1]: *** [cmTC_93503/fast] Error 2
    make[1]: Leaving directory '/home/etenal/s2e_test/build/s2e/llvm-release/CMakeFiles/CMakeTmp'**
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:48 (project)
-- Configuring incomplete, errors occurred!
See also "/home/etenal/s2e_test/build/s2e/llvm-release/CMakeFiles/CMakeOutput.log".
See also "/home/etenal/s2e_test/build/s2e/llvm-release/CMakeFiles/CMakeError.log".
/home/etenal/s2e_test/source/s2e/Makefile:162: recipe for target 'stamps/llvm-release-configure' failed
make: *** [stamps/llvm-release-configure] Error 1
make: Leaving directory '/home/etenal/s2e_test/build/s2e'
ERROR: [build] 

I don't know what I did cause these dependencies missing. What I recently did is install gcc-8 few weeks ago.

**Comment by vitalych** [comment]
Could you try building llvm-3.9 on its own. If that doesn't work, there is something wrong with your build system. Also try building the latest llvm, if that works, it would be a good time to upgrade the LLVM version that S2E uses.

**Comment by FlyRabbit** [comment]
I tried to build llvm-3.9 on its own, failed. So I have to restore the previous snapshot to fix this problem. But I still don't know how this problem happen.
BTW, every time I use `s2e build -r libs2e` to build my own plugins, is there any simple way to directly build plugins?

**Comment by vitalych** [comment]
For now, plugins are integrated in libs2e, so you have to re-build the library when you change them. I know it's slow. There is a branch with python plugin support (so that you can write your plugins in python instead of C++) which would fix most issues but @adrianherrera doesn't have time to work on it, so we are looking for volunteers to take over (https://github.com/S2E/libs2ecore/tree/improvement/python-plugins).

**Comment by FlyRabbit** [comment]
Thanks vitalych, let me understand the code first.

**Comment by FlyRabbit** [comment]
And I closed this issue.
