### ISSUE TITLE
command "s2e build" error

### ISSUE THREAD

**Issue by sobolwc** [S2E/s2e-env#288]
Hello. 
I did "s2e init $DIR" and ". s2e_activate" 
These commands completed successfully!

Then I did: "s2e build" 

I got an error (on screenshot):
![error](https://user-images.githubusercontent.com/37054694/56310172-e396c700-6153-11e9-8762-587f068458dc.jpg)

I don't know where to find the line in Makefile where i must to insert -std=c99

**Comment by vitalych** [comment]
Which ubuntu are you using?

**Comment by vitalych** [comment]
The error should be quick to fix (move the int out of the loop).

**Comment by sobolwc** [comment]
I use ubuntu 14.04 x64 ) 

Thank you! 
I move the int out of the loop and the error disappeared!

**Comment by vitalych** [comment]
Cool, please send a pull request. We don't really build/test on Ubuntu 14 anymore (16 works, 18 is preferred).
