### ISSUE TITLE
PathSearcher: clean it up and document it

### ISSUE THREAD

**Issue by vitalych** [S2E/s2e-env#297]
Also it's not clear if it works.

**Comment by everpall** [comment]
I need to pass the log file to the plugin, but I do not know how to create the log file and forward it to you right away.

I would really appreciate it if you comment on a very simple and small example.

**Comment by everpall** [comment]
Perhaps, the path searcher seems to pick up a promising path when the state is forked.

**Comment by vitalych** [comment]
This plugin will be removed. See #315.
