### ISSUE TITLE
image_build errors on i386 and x86-64 

### ISSUE THREAD

**Issue by wangray** [S2E/s2e-env#30]
Hi,

I am attempting to build on a 16.04 machine, and I get these errors when I run `s2e image_build debian-8.7.1-i386`:

```
Working dir: /nas/raywang/testing/images/.tmp-output/linux-4.9.3-i386/linux-4.9.3
/bin/bash: /nas/raywang/testing/source/guest-images/Linux/docker/make-kernel.sh: No such file or directory
/nas/raywang/testing/source/guest-images//Makefile.linux:151: recipe for target '/nas/raywang/testing/images/.stamps/linux-4.9.3-i386' failed
```

and `s2e image_build debian-8.7.1-x86_64`:

```
E: Package 'kernel-package' has no installation candidate
The command '/bin/sh -c apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends     sudo apt-file texinfo flex bison patch python unzip git bc     bzip2 wget less nano g++ gcc file libc6-dev  make     fakeroot build-essential devscripts kernel-package libncurses5-dev &&     apt-get clean &&     apt-file update' returned a non-zero code: 100
```

**Comment by adrianherrera** [comment]
Hey,

There was an issue where building images didn't work if the S2E environment was outside your home directory. It seems like this issue still exists.

Are you able to create a new environment in `/home` and try again? Failing that, you can always use `s2e image_build -d debian-8.7.1-i386` to download the image.

**Comment by wangray** [comment]
I was previously able to build in the home directory, but I've downloaded the image for now. Thanks.
