### ISSUE TITLE
error: 's2e::S2EExecutor::fork' hides overloaded virtual function

### ISSUE THREAD

**Issue by FactionCube** [S2E/s2e-env#301]
Hi,
I ran 's2e update' and 's2e build' on Ubuntu 18.04, and usually everything builds okay but today the build is giving repeated '**fork' hides overloaded virtual function**' errors:

[  8%] Building CXX object src/CMakeFiles/s2ecore.dir/S2EExecutionState.cpp.o
[100%] Linking CXX static library libtcg.a
make[5]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/i386-s2e-softmmu/libtcg'
[100%] Built target tcg
make[4]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/i386-s2e-softmmu/libtcg'
make[3]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/i386-s2e-softmmu/libtcg'
libcpu/src/op_helper.bc
make -C libs2ecore
make[3]: Entering directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/i386-s2e-softmmu/libs2ecore'
make[4]: Entering directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/i386-s2e-softmmu/libs2ecore'
make[5]: Entering directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/i386-s2e-softmmu/libs2ecore'
Scanning dependencies of target s2ecore
In file included from /media/user/VENGEUR/s2e/source/s2e/libs2ecore/src/S2EExecutionStateRegisters.cpp:11:
**In file included from /media/user/VENGEUR/s2e/source/s2e/libs2ecore/include/s2e/S2E.h:27:
/media/user/VENGEUR/s2e/source/s2e/libs2ecore/include/s2e/S2EExecutor.h:71:15: error: 's2e::S2EExecutor::fork' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    StatePair fork(klee::ExecutionState &current, const klee::ref<klee::Expr> &condition,
              ^
/media/user/VENGEUR/s2e/build/s2e/klee-release/include/klee/Executor.h:298:23: note: hidden overloaded virtual function 'klee::Executor::fork' declared here: different number of parameters (5 vs 3)
    virtual StatePair fork(ExecutionState &current, ref<Expr> condition, bool isInternal, bool deterministic = false,**
                      ^

... and there are more instantiations of this particular error as the build proceeds.

Also - I did try building specific components 's2e build -r klee'  (and later 's2e build -r libvmi'), and I was getting errors like this one:

[  6%] Building CXX object src/CMakeFiles/s2eplugins.dir/s2e/Plugins/Support/WebServiceInterface.cpp.o
make[5]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/x86_64-s2e_sp-softmmu/libs2eplugins'
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/s2eplugins.dir/all' failed
make[4]: *** [src/CMakeFiles/s2eplugins.dir/all] Error 2
make[4]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/x86_64-s2e_sp-softmmu/libs2eplugins'
Makefile:83: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/x86_64-s2e_sp-softmmu/libs2eplugins'
Makefile:36: recipe for target 'libs2eplugins/src/libs2eplugins.a' failed
make[2]: *** [libs2eplugins/src/libs2eplugins.a] Error 2
make[2]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/x86_64-s2e_sp-softmmu'
Makefile:12: recipe for target 'x86_64-s2e_sp-softmmu' failed
make[1]: *** [x86_64-s2e_sp-softmmu] Error 2
[  8%] Building CXX object src/CMakeFiles/s2eplugins.dir/s2e/Plugins/OSMonitors/ModuleDescriptor.cpp.o
[  9%] Building CXX object src/CMakeFiles/s2eplugins.dir/s2e/Plugins/OSMonitors/Windows/BlueScreenInterceptor.cpp.o
/media/user/VENGEUR/s2e/source/s2e/libs2eplugins/src/s2e/Plugins/OSMonitors/ModuleDescriptor.cpp:32:27: **error: no member named 'virtualSize' in 'vmi::SectionDescriptor'
        sd.size = section.virtualSize;**
                  ~~~~~~~ ^


Thank you for taking the time to respond to this.

**Comment by vitalych** [comment]
Could you delete the `build/stamps` folder as well as `build/klee-*` and `klee/libvmi-*`, then try again?
I'll try to debug this.

**Comment by FactionCube** [comment]
I have deleted those folders, but have come up short on the build for a different error.  

I got as far as this:

### s2e build
INFO: [build] Building S2E (release) in /media/user/VENGEUR/s2e/build/s2e
make: Entering directory '/media/user/VENGEUR/s2e/build/s2e'
make -j8 -C qemu-release  install
make[1]: Entering directory '/media/user/VENGEUR/s2e/build/s2e/qemu-release'
  LINK    tests/qemu-iotests/socket_scm_helper
  CC      qga/commands.o
  CC      qga/guest-agent-command-state.o
  CC      qga/main.o
  CC      qga/channel-posix.o
  CC      qga/commands-posix.o
  CC      qga/qapi-generated/qga-qapi-visit.o
  CC      qga/qapi-generated/qga-qapi-types.o
  CC      qga/qapi-generated/qga-qapi-commands.o
  AR      libqemuutil.a
make[1]: *** No rule to make target '/media/user/VENGEUR/s2e/source/s2e/qemu/hw/qdev-monitor.c', needed by 'qdev-monitor.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....
  CC      qemu-img.o
make[1]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/qemu-release'
/media/user/VENGEUR/s2e/source/s2e/Makefile:646: recipe for target 'stamps/qemu-release-make' failed
make: *** [stamps/qemu-release-make] Error 2
make: Leaving directory '/media/user/VENGEUR/s2e/build/s2e'
ERROR: [build] 

  RAN: /usr/bin/make --directory=/media/user/VENGEUR/s2e/build/s2e --file=/media/user/VENGEUR/s2e/source/s2e/Makefile install
  STDOUT:
  STDERR:


 I'm not sure why it had problems with the Makefile:646 recipe.  Anyway, I ran that line of the Makefile manually (_make stamps/qemu-release-make_), but inadvertently from the source/s2e folder, so it compiled and created a local source/s2e/stamps folder with two newly touched files, which I moved to the build/s2e/stamps folder, after which I reran 's2e build' and it stopped again as so:


s2e build
.
.

Scanning dependencies of target s2eplugins
make[5]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/x86_64-s2e_sp-softmmu/libs2eplugins'
make[5]: Entering directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/x86_64-s2e_sp-softmmu/libs2eplugins'
[  3%] Building CXX object src/CMakeFiles/s2eplugins.dir/s2e/Plugins/Core/Vmi.cpp.o
[  3%] Building CXX object src/CMakeFiles/s2eplugins.dir/s2e/Plugins/Core/BaseInstructions.cpp.o
[  4%] Building CXX object src/CMakeFiles/s2eplugins.dir/s2e/Plugins/Core/HostFiles.cpp.o
[  5%] Building CXX object src/CMakeFiles/s2eplugins.dir/s2e/Plugins/Support/KeyValueStore.cpp.o
[  6%] Building CXX object src/CMakeFiles/s2eplugins.dir/s2e/Plugins/Support/WebServiceInterface.cpp.o
[  8%] Building CXX object src/CMakeFiles/s2eplugins.dir/s2e/Plugins/OSMonitors/ModuleDescriptor.cpp.o
[  9%] Building CXX object src/CMakeFiles/s2eplugins.dir/s2e/Plugins/OSMonitors/Windows/BlueScreenInterceptor.cpp.o
**/media/user/VENGEUR/s2e/source/s2e/libs2eplugins/src/s2e/Plugins/OSMonitors/ModuleDescriptor.cpp:32:27: error: no member named 'virtualSize' in
      'vmi::SectionDescriptor'
        sd.size = section.virtualSize;**
                  ~~~~~~~ ^
1 error generated.
src/CMakeFiles/s2eplugins.dir/build.make:190: recipe for target 'src/CMakeFiles/s2eplugins.dir/s2e/Plugins/OSMonitors/ModuleDescriptor.cpp.o' failed
make[5]: *** [src/CMakeFiles/s2eplugins.dir/s2e/Plugins/OSMonitors/ModuleDescriptor.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/x86_64-s2e-softmmu/libs2eplugins'
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/s2eplugins.dir/all' failed
make[4]: *** [src/CMakeFiles/s2eplugins.dir/all] Error 2
make[4]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/x86_64-s2e-softmmu/libs2eplugins'
Makefile:83: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/x86_64-s2e-softmmu/libs2eplugins'
Makefile:36: recipe for target 'libs2eplugins/src/libs2eplugins.a' failed
make[2]: *** [libs2eplugins/src/libs2eplugins.a] Error 2
make[2]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/x86_64-s2e-softmmu'
Makefile:12: recipe for target 'x86_64-s2e-softmmu' failed
make[1]: *** [x86_64-s2e-softmmu] Error 2
make[5]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/x86_64-s2e_sp-softmmu/libs2eplugins'
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/s2eplugins.dir/all' failed
make[4]: *** [src/CMakeFiles/s2eplugins.dir/all] Error 2
make[4]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/x86_64-s2e_sp-softmmu/libs2eplugins'
Makefile:83: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/x86_64-s2e_sp-softmmu/libs2eplugins'
Makefile:36: recipe for target 'libs2eplugins/src/libs2eplugins.a' failed
make[2]: *** [libs2eplugins/src/libs2eplugins.a] Error 2
make[2]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/x86_64-s2e_sp-softmmu'
Makefile:12: recipe for target 'x86_64-s2e_sp-softmmu' failed
make[1]: *** [x86_64-s2e_sp-softmmu] Error 2
make[1]: Leaving directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release'
/media/user/VENGEUR/s2e/source/s2e/Makefile:192: recipe for target 'stamps/libs2e-release-make' failed
make: *** [stamps/libs2e-release-make] Error 2
make: Leaving directory '/media/user/VENGEUR/s2e/build/s2e'
ERROR: [build] 



  RAN: /usr/bin/make --directory=/media/user/VENGEUR/s2e/build/s2e --file=/media/user/VENGEUR/s2e/source/s2e/Makefile install

**Comment by vitalych** [comment]
It's definitely a problem in the Makefile. It doesn't rebuild dependencies properly. You still have something stale somewhere. Just delete the contents of the build folder and run `s2e build` again. I'll push fixes soon.

**Comment by vitalych** [comment]
Please check https://github.com/S2E/build-scripts/pull/38

**Comment by vitalych** [comment]
merged

**Comment by FactionCube** [comment]
I have checked those changes and I definitely now have them within my build.  I once again deleted the build folder and ran 's2e update' ; 's2e build' but the 'virtualSize' error is still there:


make[5]: Entering directory '/media/user/VENGEUR/s2e/build/s2e/libs2e-release/x86_64-s2e_sp-softmmu/libs2eplugins'
[  1%] Building CXX object src/CMakeFiles/s2eplugins.dir/s2e/Plugins/OSMonitors/ModuleDescriptor.cpp.o
/media/user/VENGEUR/s2e/source/s2e/libs2eplugins/src/s2e/Plugins/OSMonitors/ModuleDescriptor.cpp:32:27: error: no member named 'virtualSize' in
      'vmi::SectionDescriptor'
        sd.size = section.virtualSize;
                  ~~~~~~~ ^
1 error generated.


I have been going through various files in the source directories, and comparing them against the GitHub source, and haven't found any obvious differences in file-size, or in the content of Makefile/CMakeList.txt files.  I am still looking, though.

It might be just as quick for me to run another 's2e init' and make a fresh environment.  If I do this, can I simply save off the existing /projects, /images and /source/guest-images folders and slot them into place in a new s2e folder?

Thank you for looking into this.

**Comment by vitalych** [comment]
I think you can first try deleting the contents of the build folder. Then create a new env if that doesn't work, but make sure that it is in the same location as the old one (rename the old one first).
