### ISSUE TITLE
s2e init  error  on Ubuntu 14.04

### ISSUE THREAD

**Issue by jiwonjoung** [S2E/s2e-env#303]
s2e init /apollo/s2e
/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a release (2.7.7+) that supports hmac.compare_digest as soon as possible.
  utils.PersistentlyDeprecated2018,
INFO: [init] Creating environment in /apollo/s2e
INFO: [init] Installing S2E dependencies
Hit http://storage.googleapis.com stable InRelease
Ign http://archive.ubuntu.com trusty InRelease                                 
Hit http://archive.ubuntu.com trusty-updates InRelease                         
Hit http://archive.ubuntu.com trusty-security InRelease                        
Hit http://archive.ubuntu.com trusty-backports InRelease                       
Ign http://developer.download.nvidia.com  InRelease                            
Ign http://ppa.launchpad.net trusty InRelease                                  
Hit http://ppa.launchpad.net trusty InRelease                                  
Hit http://ppa.launchpad.net trusty InRelease                                  
Hit http://ppa.launchpad.net trusty InRelease                                  
Hit http://packages.ros.org trusty InRelease                                   
Hit https://dl.yarnpkg.com stable InRelease                                    
Hit http://developer.download.nvidia.com  Release.gpg                          
Hit http://developer.download.nvidia.com  Release                              
Hit http://archive.ubuntu.com trusty Release.gpg                               
Hit http://archive.ubuntu.com trusty Release                                   
Hit http://ppa.launchpad.net trusty Release.gpg                             
Hit http://ppa.launchpad.net trusty Release      
Hit http://storage.googleapis.com stable/jdk1.8 amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/main Sources
Hit http://archive.ubuntu.com trusty-updates/restricted Sources
Hit http://archive.ubuntu.com trusty-updates/universe Sources    
Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages 
Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/main i386 Packages   
Hit http://archive.ubuntu.com trusty-updates/restricted i386 Packages
Hit http://archive.ubuntu.com trusty-updates/universe i386 Packages   
Hit http://archive.ubuntu.com trusty-security/main Sources            
Hit http://archive.ubuntu.com trusty-security/restricted Sources  
Hit http://archive.ubuntu.com trusty-security/universe Sources   
Hit http://archive.ubuntu.com trusty-security/main amd64 Packages
Hit http://archive.ubuntu.com trusty-security/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-security/universe amd64 Packages 
Hit http://archive.ubuntu.com trusty-security/main i386 Packages  
Hit http://archive.ubuntu.com trusty-security/restricted i386 Packages
Hit http://archive.ubuntu.com trusty-security/universe i386 Packages
Hit http://archive.ubuntu.com trusty-backports/universe amd64 Packages
Hit http://archive.ubuntu.com trusty-backports/universe i386 Packages          
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://packages.ros.org trusty/main amd64 Packages                         
Hit http://packages.ros.org trusty/main i386 Packages                          
Hit http://developer.download.nvidia.com  Packages                             
Hit https://dl.yarnpkg.com stable/main amd64 Packages                          
Hit https://dl.yarnpkg.com stable/main i386 Packages                           
Hit http://archive.ubuntu.com trusty/main Sources                              
Hit http://archive.ubuntu.com trusty/restricted Sources                        
Hit http://ppa.launchpad.net trusty/main Sources                               
Hit http://archive.ubuntu.com trusty/universe Sources                          
Hit http://archive.ubuntu.com trusty/main amd64 Packages                       
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages                 
Hit http://archive.ubuntu.com trusty/universe amd64 Packages                   
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://archive.ubuntu.com trusty/main i386 Packages                        
Hit http://archive.ubuntu.com trusty/restricted i386 Packages                  
Hit http://archive.ubuntu.com trusty/universe i386 Packages                    
Reading package lists... Done                                                  
W: Ignoring Provides line with DepCompareOp for package gdb-minimal
W: Ignoring Provides line with DepCompareOp for package gdb-minimal
W: You may want to run apt-get update to correct these problems
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libsdl1.2-dev' instead of 'libsdl-dev'
bison is already the newest version.
build-essential is already the newest version.
cmake is already the newest version.
flex is already the newest version.
g++-multilib is already the newest version.
gcc-multilib is already the newest version.
genisoimage is already the newest version.
lib32ncurses5 is already the newest version.
lib32ncurses5-dev is already the newest version.
libboost-dev is already the newest version.
libboost-regex-dev is already the newest version.
libboost-serialization-dev is already the newest version.
libboost-system-dev is already the newest version.
libbsd-dev is already the newest version.
libmemcached-dev is already the newest version.
libncurses5-dev is already the newest version.
libprotobuf-dev is already the newest version.
libreadline-dev is already the newest version.
libsigc++-2.0-dev is already the newest version.
libx32ncurses5-dev is already the newest version.
pkg-config is already the newest version.
protobuf-compiler is already the newest version.
python-dev is already the newest version.
python-docutils is already the newest version.
texinfo is already the newest version.
xz-utils is already the newest version.
jigdo-file is already the newest version.
libhivex-bin is already the newest version.
libjemalloc-dev is already the newest version.
libvdeplug-dev is already the newest version.
mingw-w64 is already the newest version.
pxz is already the newest version.
libncurses5-dev:i386 is already the newest version.
binutils-dev is already the newest version.
fuse is already the newest version.
git is already the newest version.
lcov is already the newest version.
libc6-dev-i386 is already the newest version.
libelf-dev is already the newest version.
libglib2.0-dev is already the newest version.
libiberty-dev is already the newest version.
libpixman-1-dev is already the newest version.
libpq-dev is already the newest version.
libsdl1.2-dev is already the newest version.
nasm is already the newest version.
wget is already the newest version.
zlib1g-dev is already the newest version.
docker.io is already the newest version.
jq is already the newest version.
libdwarf-dev is already the newest version.
libguestfs-tools is already the newest version.
p7zip-full is already the newest version.
python-pip is already the newest version.
qemu is already the newest version.
libelf-dev:i386 is already the newest version.
libglib2.0-0:i386 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 287 not upgraded.
W: Ignoring Provides line with DepCompareOp for package gdb-minimal
W: Ignoring Provides line with DepCompareOp for package gdb-minimal
W: You may want to run apt-get update to correct these problems
INFO: [init] Fetching repo
SUCCESS: [init] Fetched repo
INFO: [init] Fetching manifest from https://github.com/S2E
Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
remote: Counting objects: 1, done
remote: Finding sources: 100% (105/105)
remote: Total 105 (delta 28), reused 105 (delta 28)
Receiving objects: 100% (105/105), 184.38 KiB | 0 bytes/s, done.
Resolving deltas: 100% (28/28), completed with 16 local objects.
From https://gerrit.googlesource.com/git-repo
   d92464e..0c0e934  master     -> origin/master
   13f323b..c5b0e23  stable     -> origin/stable
 * [new tag]         v1.13.3    -> v1.13.3
Traceback (most recent call last):
  File "/apollo/s2e/source/s2e/.repo/repo/main.py", line 547, in <module>
    _Main(sys.argv[1:])
  File "/apollo/s2e/source/s2e/.repo/repo/main.py", line 522, in _Main
    result = repo._Run(argv) or 0
  File "/apollo/s2e/source/s2e/.repo/repo/main.py", line 181, in _Run
    cmd_event = cmd.event_log.Add(name, event_log.TASK_COMMAND, start)
  File "/apollo/s2e/source/s2e/.repo/repo/event_log.py", line 73, in Add
    'id': (kind, _NextEventId()),
  File "/apollo/s2e/source/s2e/.repo/repo/event_log.py", line 173, in _NextEventId
    with _EVENT_ID.get_lock():
AttributeError: __exit__
ERROR: [init] 
``
  RAN: /s2e/install/bin/repo init -u https://github.com/S2E/manifest

  STDOUT:

  STDERR:

**Comment by jiwonjoung** [comment]
there is very little information about why this is happening -- any suggestions?

**Comment by vitalych** [comment]
First time I see this. Looks like the `repo` tool does not work on your setup.
Are you using Ubuntu 18.04 LTS?

**Comment by jiwonjoung** [comment]
trying to install on 14.04

**Comment by vitalych** [comment]
We only support 16.04 and 18.04, so I can't help you much here, sorry. But if you can find a fix, don't hesitate to submit it.
