### ISSUE TITLE
Interpreting S2E output

### ISSUE THREAD

**Issue by jiwonjoung** [S2E/s2e-env#308]
Hello, I've looked over the S2E documentation several times but I cannot seem to figure out how to interpret the S2E output. 

KLEE generates test cases with sample inputs that trigger failure. What kind of output does S2E generate?

**Comment by vitalych** [comment]
Thanks. Please use s2e-dev mailing list for general questions.
S2E generates different kinds of test cases depending on the use case.
- If you use symbolic files, it automatically creates concrete files in `s2e-last`
- If you use s2e_make_symbolic, you can either grep for `TestCaseGenerator` in s2e-last/debug.txt, or use `s2e execution_trace` to generate a json trace that contains test cases for each state (among other info).

**Comment by vitalych** [comment]
Related https://github.com/S2E/s2e-env/issues/236
