### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by priyangavij** [S2E/s2e-env#309]
I am using Ubuntu 16.04.
There is no makefile present and therefore 's2e build' is not working.
How to rectify this?
Please help me out.
![Screenshot (116)](https://user-images.githubusercontent.com/51303271/61559541-c4435a80-aa1e-11e9-98cd-0277effc9a3a.png)

**Comment by vitalych** [comment]
Could you please paste all the commands you made as well as the contents of the source folder?

**Comment by priyangavij** [comment]
sudo apt-get install git gcc python python-dev virtualenv

git clone https://github.com/s2e/s2e-env.git
cd s2e-env

virtualenv venv
. venv/bin/activate
pip install --upgrade pip
pip install .

s2e init /home/user/s2e

. s2e_activate

These were the commands used

**Comment by priyangavij** [comment]
guest-images
s2e
s2e-linux-kernel
testsuite

These are present in the source folder

**Comment by vitalych** [comment]
Ah I meant in the s2e folder.

**Comment by vitalych** [comment]
It would have been nice to explain what the problem was before closing the issue, in case others encounter the same.

**Comment by priyangavij** [comment]
This problem did not arise with Ubuntu 18.04.
