### ISSUE TITLE
Add BIOS target to s2e-env

### ISSUE THREAD

**Issue by priyangavij** [S2E/s2e-env#310]
How do I test a binary of a bios using the s2e tool?
What are the commands to be used?

**Comment by vitalych** [comment]
s2e-env does not support BIOS projects directly, but you can tweak a Linux project to make it work.
- Create an empty Linux project
- Modify launch-s2e.sh: remove -loadvm ready and add -bios flag to QEMU

Related issue: https://github.com/S2E/s2e-env/issues/196

**Comment by priyangavij** [comment]
Should -bios flag be added as QEMU Extra Flags in the launch-s2e.sh?

**Comment by priyangavij** [comment]
s2e new_project --image guest1 /home/host/bios.bin

bios.bin is a binary of a bios.

Traceback (most recent call last):
  File "/home/host/venv/bin/s2e", line 10, in <module>
    sys.exit(main())
  File "/home/host/venv/local/lib/python2.7/site-packages/s2e_env/manage.py", line 190, in main
    manager.execute()
  File "/home/host/venv/local/lib/python2.7/site-packages/s2e_env/manage.py", line 179, in execute
    self.fetch_command(subcommand).run_from_argv(self._argv)
  File "/home/host/venv/local/lib/python2.7/site-packages/s2e_env/command.py", line 158, in run_from_argv
    output = self.execute(*args, **cmd_options)
  File "/home/host/venv/local/lib/python2.7/site-packages/s2e_env/command.py", line 183, in execute
    self.handle(*args, **options)
  File "/home/host/venv/local/lib/python2.7/site-packages/s2e_env/commands/new_project.py", line 169, in handle
    _handle_with_file(options.pop('target'), proj_class, *args, **options)
  File "/home/host/venv/local/lib/python2.7/site-packages/s2e_env/commands/new_project.py", line 71, in _handle_with_file
    target = Target.from_file(target_path, proj_class)
  File "/home/host/venv/local/lib/python2.7/site-packages/s2e_env/commands/project_creation/target.py", line 169, in from_file
    path_to_analyze)
s2e_env.commands.project_creation.target.TargetError: Could not determine architecture for /home/host/bios.bin

This is the error I get while running the above mentioned command.

**Comment by vitalych** [comment]
As I mentioned, s2e-env does not support bios binaries. You can't do that. Instead, create an empty Linux project and manually change s2e-launch.sh.

**Comment by vitalych** [comment]
E.g., `s2e new_project -n bios_project -i debian-9.2.1-i386 --no-target --type linux`

**Comment by vitalych** [comment]
Then edit launch-s2e.sh to remove `-loadvm ready`. Then launch like this:
`./launch-s2e -bios /path/to/your/bios`.

Note that most S2E plugins will not work. All you will be able to do is manually call `s2e_make_symbolic` from the BIOS binary, unless you write your own bios monitor plugin yourself (similar to LinuxMonitor and WindowsMonitor).

**Comment by vitalych** [comment]
Once you manage to set everything up manually, don't hesitate to add support for it in s2e-env and send a pull request.

**Comment by priyangavij** [comment]
-loadvm $QEMU_SNAPSHOT $*
This is what I found in launch-s2e.sh. 
Should I remove this?

**Comment by vitalych** [comment]
Only `-loadvm $QEMU_SNAPSHOT`. Leave the $*

**Comment by priyangavij** [comment]
Where can I find the output after I run ./launch-s2e -bios /path/to/your/bios?

**Comment by vitalych** [comment]
Like with any other binary, in `s2e-last/debug.txt`. Note that you probably won't see much out of the box.
You can also enable graphics outputs in launch-s2e.sh or redirect the output to the console by modifying QEMU command line arguments).

**Comment by priyangavij** [comment]
> s2e-env does not support BIOS projects directly, but you can tweak a Linux project to make it work.
> 
> * Create an empty Linux project
> * Modify launch-s2e.sh: remove -loadvm ready and add -bios flag to QEMU
> 
> Related issue: #196

Why does S2E not support bios binaries?

**Comment by vitalych** [comment]
The S2E engine supports any x86 code, so your BIOS will run. Hoever, s2e-env does not support it. Therefore, you will have to set up the configuration files on your own.

**Comment by priyangavij** [comment]
Is it possible to generate PoV for a bios binary in S2E

**Comment by vitalych** [comment]
Yes, the TestCaseGenerator plugin should work as usual.

**Comment by priyangavij** [comment]
How do I input the bios binary in the command?

**Comment by vitalych** [comment]
Add -bios flag to qemu, as explained above.

**Comment by priyangavij** [comment]
qemu-system-x86_64: Length mismatch: pc.bios: 0x40000 in != 0x400000: Invalid argument
qemu-system-x86_64: error while loading state for instance 0x0 of device 'ram'
qemu-system-x86_64: Error -22 while loading VM state

This is the error I get when I run "./launch-s2e.sh -bios /home/ubuntu/bios.bin".

**Comment by vitalych** [comment]
Please remove -loadvm from launch-s2e.sh (again as explained above)

**Comment by priyangavij** [comment]
QEMU_EXTRA_FLAGS=$(jq -r -bios '.qemu_extra_flags' "$IMAGE_JSON")

 $GDB $QEMU $QEMU_DRIVE \
        -k en-us $GRAPHICS -monitor null -m $QEMU_MEMORY -enable-kvm \
        -serial file:serial.txt $QEMU_EXTRA_FLAGS \
        $*

Just making sure if this is the correct usage.

**Comment by priyangavij** [comment]
./launch-s2e.sh: line 86: 33275 Aborted                 (core dumped) LD_PRELOAD=$LIBS2E $QEMU $QEMU_DRIVE -k en-us $GRAPHICS -monitor null -m $QEMU_MEMORY -enable-kvm -serial file:serial.txt $QEMU_EXTRA_FLAGS $*

This is the error I get after removing -loadvm ready from launch-s2e.sh

**Comment by vitalych** [comment]
In this case, I don't know, you'll have to get the stack trace. I might look into it when I get some time.

**Comment by priyangavij** [comment]
How do I retrieve the stack trace?

**Comment by vitalych** [comment]
./launch-s2e.sh debug -bios...

**Comment by priyangavij** [comment]
"./launch-s2e.sh -bios /path/to/bios" throws a warning stating unknown option '-bios'

**Comment by priyangavij** [comment]
clang-3.9: error: unable to execute command: Killed
clang-3.9: error: linker command failed due to signal (use -v to see invocation)
tools/clang/tools/driver/CMakeFiles/clang.dir/build.make:218: recipe for target 'bin/clang-3.9' failed
make[3]: *** [bin/clang-3.9] Error 254
make[3]: Leaving directory '/home/ubuntu/s2e/build/s2e/llvm-debug'
CMakeFiles/Makefile2:10953: recipe for target 'tools/clang/tools/driver/CMakeFiles/clang.dir/all' failed
make[2]: *** [tools/clang/tools/driver/CMakeFiles/clang.dir/all] Error 2
make[2]: Leaving directory '/home/ubuntu/s2e/build/s2e/llvm-debug'
Makefile:151: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ubuntu/s2e/build/s2e/llvm-debug'
/home/ubuntu/s2e/source/s2e/Makefile:195: recipe for target 'stamps/llvm-debug-make' failed
make: *** [stamps/llvm-debug-make] Error 2
make: Leaving directory '/home/ubuntu/s2e/build/s2e'

 
"s2e build --debug" throws this error. How do I resolve it?

**Comment by vitalych** [comment]
No idea. Something killed clang. Do you have enough memory for the build?

**Comment by vitalych** [comment]
4GB is probably not enough. Check dmsg to see if there were out of memory conditions.

**Comment by priyangavij** [comment]
8 GB RAM solved the problem.

**Comment by priyangavij** [comment]
./launch-s2e.sh debug -bios
jq: Unknown option -bios
Use jq --help for help with command-line options,
or see the jq manpage, or online docs  at https://stedolan.github.io/jq
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/ubuntu/s2e/build/s2e/qemu-debug/x86_64-softmmu/qemu-system-x86_64...done.
(gdb) 


What needs to be given as input for gdb now?

**Comment by vitalych** [comment]
S2E does n ot support BIOS targets officially now, so you will have to look at the script and fix it yourself. Something may be wrong in one of these lines, though I fail to see how: https://github.com/S2E/s2e-env/blob/master/s2e_env/templates/launch-s2e.sh#L30

**Comment by vitalych** [comment]
This is now supported by s2e-env
