### ISSUE TITLE
guest-images: recent win10 requires product key

### ISSUE THREAD

**Issue by mpuzz** [S2E/s2e-env#316]
Hello,

I'm trying to build my own image from the latest Win10 (1903) image available on MSDN.

I have already built the guest-tools for this release, including the s2e.sys driver for its specific kernel.

The issue starts when building the image with `s2e image-build`.
I modified the image.json and Makefile.windows files in guest-images to include the new image, but when I run the command it hangs when Windows is booting in QEMU from the CD-ROM.
Debugging the problem with --gui, I discovered Windows is asking for a product key.
This behavior is different from what happens when the same image runs in a VM, where it doesn't require any ProductKey to start.

Do you think is there something in your pipeline that makes Windows behave like this?
Any ideas on how I can solve/debug this issue?

Thanks,
Dario

**Comment by vitalych** [comment]
That's strange. The current image does not require a product key (win10 enterprise).
If it insists on one, you should be able to add it to the json and the unattended install xml template file (using {{os.product_key}}).
https://github.com/S2E/guest-images/blob/master/Windows/Autounattend.xml.template

**Comment by mpuzz** [comment]
Alright, I managed to get the installation phase to work.
Apparently newer Windows 10 builds need a generic Product Key in the unattended xml file.
Once this is provided, the image building scripts run smoothly

**Comment by vitalych** [comment]
Thanks!  Could you add to the issue which key it is?

**Comment by mpuzz** [comment]
The key is VK7JG-NPHTM-C97JM-9MPGT-3V66T
It works for Windows 10 release 1903. It may work with other release too, but I didn't try

**Comment by vitalych** [comment]
Should be fixed together with #393
