### ISSUE TITLE
How to get the value of the gs register

### ISSUE THREAD

**Issue by MRLEE123456** [S2E/s2e-env#320]
Hello!
In my experiment I found that the value of the acquired gs register is the same as the value of the ebp register.By examining the relevant macro definitions, I found that the values of R_GS and R_EBP are the same.
`#define R_EAX 0
#define R_ECX 1
#define R_EDX 2
#define R_EBX 3
#define R_ESP 4
#define R_EBP 5
#define R_ESI 6
#define R_EDI 7

#define R_AL 0
#define R_CL 1
#define R_DL 2
#define R_BL 3
#define R_AH 4
#define R_CH 5
#define R_DH 6
#define R_BH 7

#define R_ES 0
#define R_CS 1
#define R_SS 2
#define R_DS 3
#define R_FS 4
#define R_GS 5
`

**Comment by vitalych** [comment]
You need to read CPUState::segs[R_GS] instead of CPUState::regs[R_GS]. The latter is for general purpose registers.
