### ISSUE TITLE
Concolic execution in latest S2E

### ISSUE THREAD

**Issue by mpuzz** [S2E/s2e-env#322]
Hello,
I cannot understand whether S2E still performs concolic testing after #235 was merged.
If this is the case, how can one specify the concrete seed for a symbolic value?

**Comment by vitalych** [comment]
Yes. Just rename s2e_make_concolic to s2e_make_symbolic. It will work as before, using whatever concrete values are there.

Note that what S2E calls "concolic execution" is vers different from the original concolic execution introduced by DAST. See for details: http://s2e.systems/docs/Howtos/Concolic.html
