### ISSUE TITLE
How to make symbolization of file data?

### ISSUE THREAD

**Issue by danchou-ssr** [S2E/s2e-env#325]
c language code is as follows:

`
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <fcntl.h>  

int main(int argc, char **argv) { 
    FILE* hFile = NULL;
    char str[0x1000] = { 0 };
    int fileSize = 0;
    int result = 0;
    
    printf("target file : %s\n", argv[1]);
    if (!strlen(argv[1])) { 
    	return 0;
    }

    hFile = fopen(argv[1],"rb");  
    if(hFile == NULL) { 
       return 0;
    }  

    fseek(hFile, 0L, SEEK_END); 
    fileSize = ftell(hFile); 
    fseek(hFile, 0L, SEEK_SET); 
    if (fileSize > 3) { 
	return 0;
    }
    result = fread(str, fileSize, 1, hFile);	

    if (str[0] == '\n' || str[1] == '\n') {
        printf("yc Not enough characters\n");
    } else {
        if (str[0] >= 'a' && str[0] <= 'z') {
            printf("yc First char is lowercase\n");
        } else {
            printf("yc First char is not lowercase\n");
        }

        if (str[0] >= '0' && str[0] <= '9') {
            printf("yc First char is a digit\n");
        } else {
            printf("yc First char is not a digit\n");
        }

        if (str[0] == str[1]) {
            printf("yc First and second chars are the same\n");
        } else {
            printf("yc First and second chars are not the same\n");
        }
    }
    return 0;
}
`

I use @@ as a parameter when creating an s2e project,  command is as follows:

s2e new_project -i debian-9.2.1-i386 /home/fire/s2e_tutorial/tutorial_openfile_sym/tutorial_openfile_sym @@

but did not create some branches based on symbol data.

do i still need to modify the bootstrap.sh file?

**Comment by vitalych** [comment]
Issue unclear. Needs to attach project archive to reproduce. Closing for now.
