### ISSUE TITLE
s2e build failing

### ISSUE THREAD

**Issue by Owlz** [S2E/s2e-env#33]
I'm attempting to get S2E running, however S2E build is failing with the following:

```
ar rcu liblua.a lapi.o lcode.o lctype.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o lundump.o lvm.o lzio.o lauxlib.o lbaselib.o lbitlib.o lcorolib.o ldblib.o liolib.o lmathlib.o loslib.o lstrlib.o ltablib.o loadlib.o linit.o
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib liblua.a
gcc -o lua   lua.o liblua.a -lm -Wl,-E -ldl
gcc -o luac   luac.o liblua.a -lm -Wl,-E -ldl
make[3]: Leaving directory '/home/user/opt/s2e/build/s2e/lua-5.2.4/src'
make[2]: Leaving directory '/home/user/opt/s2e/build/s2e/lua-5.2.4/src'
make[1]: Leaving directory '/home/user/opt/s2e/build/s2e/lua-5.2.4'
touch stamps/lua-make
mkdir -p libvmi-release
mkdir -p llvm-release
wget http://llvm.org/releases/3.9.0/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-16.10.tar.xz
--2017-07-06 20:45:47--  http://llvm.org/releases/3.9.0/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-16.10.tar.xz
Resolving llvm.org (llvm.org)... 54.67.122.174
Connecting to llvm.org (llvm.org)|54.67.122.174|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://releases.llvm.org/3.9.0/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-16.10.tar.xz [following]
--2017-07-06 20:45:47--  http://releases.llvm.org/3.9.0/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-16.10.tar.xz
Resolving releases.llvm.org (releases.llvm.org)... 151.101.32.204
Connecting to releases.llvm.org (releases.llvm.org)|151.101.32.204|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-07-06 20:45:48 ERROR 404: Not Found.

/home/user/opt/s2e/source/s2e/Makefile:164: recipe for target 'clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-16.10.tar.xz' failed
make: *** [clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-16.10.tar.xz] Error 8
make: Leaving directory '/home/user/opt/s2e/build/s2e'
ERROR: [build]

  RAN: /usr/bin/make --directory=/home/user/opt/s2e/build/s2e --file=/home/user/opt/s2e/source/s2e/Makefile install

  STDOUT:


  STDERR:

```

For reference, 16.10 is the Ubuntu version I am running, however it is __not__ a valid download for LLVM (http://releases.llvm.org/download.html#3.9.0)

**Comment by adrianherrera** [comment]
Hi Owlz,

Yeah, so the issue is that there is no pre-packaged LLVM 3.9.0 binary for Ubuntu 16.10. Looking at http://releases.llvm.org/download.html the only prepackaged Ubuntu 16.10 binaries are for LLVM 4.0, which S2E does not support.

I see that in Issue #34 that you "manually set the llvm download". Did you just modify the Makefile and hard code the Ubuntu 16.04 download? It would be good to get this fixed for other users who are also using Ubuntu 16.10.

Regards,
Adrian

**Comment by Owlz** [comment]
Yep. So I just hard coded the Ubuntu 16.04 binary in the make file and it
works fine on 16.10. I've had to use that trick previously actually for
installing llvm. In fact, my guess is 16.04 download would work on 17.x as
well since 16.04 is the current LTS release.

**Comment by adrianherrera** [comment]
Ok cool, I figured as much.

For now I'm just going to draw a line in the sand and say we only support the 14.04 and 16.04 LTS releases (in fact I thought this was written somewhere, but I could be mistaken) and close these issues. Feel free to send some PRs if you can get it working automatically in the Makefile.

There is also a Dockerfile available, so if required you should be able to use this to build S2E to Ubuntu 16.10.

**Comment by chahakmittal** [comment]
What about this build error in ubuntu 18 ?

**Comment by vitalych** [comment]
Can you please open a new issue and paste the errors you have?
