### ISSUE TITLE
s2e build issue

### ISSUE THREAD

**Issue by tashfia-r** [S2E/s2e-env#352]
Hi, when I tried to build s2e, the following errors are showing up-
 recipe for target 'stamps/tools-release-make' failed
make: *** [stamps/tools-release-make] Error 2

I am not sure what the problem is. Please help.

**Comment by tashfia-r** [comment]
Hi, when I tried to build s2e, the following errors are showing up-
recipe for target 'stamps/tools-release-make' failed
make: *** [stamps/tools-release-make] Error 2

This error was also showing in the log -
/usr/include/glib-2.0/glib/gtypes.h:32:10: fatal error: 'glibconfig.h' file not found
#include <glibconfig.h>


I am not sure what the problem is. Please help.

**Comment by vitalych** [comment]
Please see https://github.com/S2E/s2e-env/issues/347

**Comment by tashfia-r** [comment]
do I have to run the commands in the docker instead of init and then build? or after running s2e init use docker and then build?

**Comment by vitalych** [comment]
No need to build in docker, all you need is to install the missing packages. Make sure that you have Ubuntu 18 on the host. If not not, you can apply the workaround mentioned in the linked issue.

**Comment by tashfia-r** [comment]
OK. let me try
