### ISSUE TITLE
Running bios in s2e-env

### ISSUE THREAD

**Issue by tashfia-r** [S2E/s2e-env#361]
Hi, I saw a previous issue #310. My case is also similar. I want to run bios binary. I did everything you suggested in that issue, modified launch.sh, built s2e in debug mode and ran launch.sh. Then they showed something like the following -

GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/tashfia/s2e/build/s2e/qemu-debug/x86_64-softmmu/qemu-system-x86_64...done.
(gdb) 
What should be the input for gdb? Can you please help?

**Comment by vitalych** [comment]
Just type `r` to run it.

**Comment by tashfia-r** [comment]
how do I know that it has been run successfully? Or as s2e-env doesn't support bios binary, I have to do something else?

**Comment by vitalych** [comment]
I suggest that you checkout `s2ebios` (https://www.seabios.org/SeaBIOS), add some S2E instructions there (e.g., `s2e_message`), then run it in QEMU (`-bios` flag).
S2E does not have plugins specifically designed for BIOS for now, so to insert symbolic data into it, you will have to put `s2e_make_symbolic` manually.

**Comment by tashfia-r** [comment]
Where should I insert s2e_message? There are many files in Sea_bios, so I am confused.

**Comment by vitalych** [comment]
The place doesn't really matter. Somewhere in the C code that gets executed. The point is for you to see if it ran successfully. Close to the place you want to test could be a good start.

**Comment by tashfia-r** [comment]
What should I do if I want to do the symbolic execution of bios binaries just like linux binaries and produce concrete tests?

**Comment by vitalych** [comment]
You will have to insert `s2e_make_symbolic` and `s2e_kill_state` in your bios code manually.
See http://s2e.systems/docs/Tutorials/BasicLinuxSymbex/SourceCode.html

**Comment by tashfia-r** [comment]
Do I have to convert the bios binary to c code and then insert s2e instructions? The manual shows an execution of c code, not binary. If I insert s2e instructions in bios binary, it shows error.

**Comment by vitalych** [comment]
You should have the source of the bios. If not, you would have to patch the binary or write a plugin to inject symbolic data.

**Comment by tashfia-r** [comment]
I have the source code of tianocore bios. But there are so many codes and the codes that I got to explore didn't contain any proper function that I can replace with s2e_make_symbolic. And also their functionality is dependent on other codes too. So when I compile just one code, it shows error. Is it necessary for one code to be self-functional to modify to be able to run in s2e environment? Please help.

**Comment by vitalych** [comment]
AFAIK, tianocore lets you build your own apps that you can run from the UEFI command line. Perhaps you can start from there. Write your own hello world app that includes s2e.h and makes some data symbolic.

**Comment by tashfia-r** [comment]
Do I have to write s2e.h? What it will contain?

**Comment by vitalych** [comment]
You don't have to write s2e.h. It is already provided by S2E. You may need to cut out things that don't compile though (mostly printfs...).

**Comment by vitalych** [comment]
https://github.com/S2E/s2e/blob/master/guest/common/include/s2e/s2e.h
