### ISSUE TITLE
s2e build error

### ISSUE THREAD

**Issue by Owlz** [S2E/s2e-env#38]
```
Install the project...
-- Install configuration: ""
-- Up-to-date: /home/s2e/s2e/install/bin/guest-tools64/include/s2e/s2e.h
-- Up-to-date: /home/s2e/s2e/install/bin/guest-tools64/include/s2e/opcodes.h
-- Installing: /home/s2e/s2e/install/bin/guest-tools64/./s2ecmd.exe
-- Installing: /home/s2e/s2e/install/bin/guest-tools64/./s2eget.exe
-- Installing: /home/s2e/s2e/install/bin/guest-tools64/./s2eput.exe
make[1]: Leaving directory '/home/s2e/s2e/build/s2e/guest-tools64-win'
rm clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-16.04make: unlink: clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-16.04: Is a directory

make: Leaving directory '/home/s2e/s2e/build/s2e'
SUCCESS: [build] S2E built
```

**Comment by adrianherrera** [comment]
Hey Owlz,

Sorry, what exactly is the issue? Did it not build successfully despite saying "SUCCESS"? Or is it because it failed to remove clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-16.04? You'll need to provide some more details than just part of the output.

~Adrian

**Comment by Owlz** [comment]
Looks like it installed, however one of the last steps is to remove the directory. It seems to not have a "-r" or whatever flag is needed to recursively remove a directory. This is the failure.

**Comment by adrianherrera** [comment]
This is not really a big deal if the build is successful. TBH I'm not even sure where that `rm` command comes from, it's not explicit in our Makefile.
