### ISSUE TITLE
Makefile: install guest-tools in debug builds

### ISSUE THREAD

**Issue by LalaNguyen** [S2E/s2e-env#385]
Hi,

I want to understand how S2E analyzes a window driver. I have been following the [Windows setting](http://s2e.systems/docs/WindowsEnvSetup.html). I have finished up to the part that requires updating the boostrap.sh to run the driver. I built the sample driver in Windows 10 64x version 1803 and tried to run it in the windows 10 64x version 1703 (since this is the only windows 10 that S2E supports). Windows guest-tools are built manually following [this tutorial](https://github.com/S2E/s2e/tree/master/guest) and installed in s2e/bin/guest-tools64. All windows are not activated because I do not have production keys.

Unfortunately, after running the ./launch-s2e debug, s2e seems to stuck. Investigating the debug log gives me the last printed line: "[State 0] HostFiles: opening bootstrap.sh". Enabling the graphic interface for QEMU, I saw that the s2eget and s2ecmd crash in the guest VM, which probably the main cause of the stuck.

I suspect that I did not build the guest-tools64 correctly, can someone help me with this matter?

Minh

**Comment by vitalych** [comment]
Could you please tell where they crash (stack trace, instruction...)?
Any logs/screenshots (serial.txt, debug.txt.)?

**Comment by LalaNguyen** [comment]
Hi, 

I attached the debug log and also the screenshot when run with QEMU graphic. the serial.txt is empty.

When running s2e debug mode without graphic, it seems like s2e is stucked rather than crash... I am guessing that the problem may be related to the guest-tools64 that I cross-compiled but I am not sure what went wrong.


[debug.txt](https://github.com/S2E/s2e-env/files/4224754/debug.txt)

![crash](https://user-images.githubusercontent.com/2168614/74829810-cff85600-534c-11ea-87aa-c7d34ebb47a0.png)

**Comment by vitalych** [comment]
Normally, s2ecmd and s2eget are built on Linux by the S2E build system using mingw. You shouldn't build them on Windows. You need windows to build the driver and the tools that are in guest/windows.

In case you need to modify s2ecmd/s2eget or other common tools, run this:
```
cd $S2EENVbuild/guest-tools64-win && make install
```

**Comment by LalaNguyen** [comment]
Hi, s2ecmd and s2eget are built on Linux. I did not build it on Windows, only the sample driver was built on Windows.

One strange thing is that after the s2e build --debug, the guest-tools64 was not created under $S2EDIR/install/bin and hence, was missing. So I used the following lines to install the guest-tools64:
```
mkdir guest-tools64
cd guest-tools64
cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-windows-x86_64.cmake
make DESTDIR=$S2EDIR/install/bin/guest-tools64
```
I organized the guest-tools64 a little so that it looks like the tree belows:
guest-tools64
|--->include
|------------>s2e
|------------------------->opcodes.h
|------------------------->s2e.h
|--->s2ecmd.exe
|--->s2eget.exe
|--->s2eput.exe 

I am trying to rebuild the s2e in release mode to see whether it helps fix the issue.

**Comment by vitalych** [comment]
You may want to check the Makefile on how to configure it properly:
https://github.com/S2E/s2e/blob/master/Makefile#L778

Note that guest tools are not built in debug mode, they are a separate component.
https://github.com/S2E/s2e/blob/master/Makefile#L151

**Comment by vitalych** [comment]
If it still doesn't work, it would be good to run it in windbg in the guest to check where it crashes.
Windbg is not currently installed in the guest, it would be useful to add it here: https://github.com/S2E/guest-images/blob/master/Makefile.windows#L28

**Comment by LalaNguyen** [comment]
I got it, thank for your help! My 4-core PC is quite slow so I will get back to you when I try out your suggestions properly :D

**Comment by LalaNguyen** [comment]
Hi, after rebuilding the s2e in non-debug mode, I rebuilt the Windows image windows-10ent1703-x86_64 again. The window image has the expected hash.

However, the image_build process failed at disabling the window defender. I tried to comment out this script in Makefile.Windows and retried again. Afterwards, the build process was succeeded. Is it ok to leave this script out ?

Here is my log file for installing the guest image.
[post_install_serial1.txt](https://github.com/S2E/s2e-env/files/4229390/post_install_serial1.txt)

P/s: About the s2eget and s2ecmd issue, my guest-tools64 folder was incomplete comparing to the folder that s2e was expecting. So configure it probably helps addressing the problem :)

**Comment by vitalych** [comment]
You may be missing the libguestfs-tools package. It's odd, because it should be installed here: https://github.com/S2E/s2e-env/blob/master/s2e_env/dat/config.yaml#L43

**Comment by LalaNguyen** [comment]
I just checked it, the package is installed.

`[S2E:s2e] (venv) lala@lala-ThinkCentre-M800:~/s2e$ apt list --installed | grep libguestfs

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libguestfs-perl/bionic-updates,now 1:1.36.13-1ubuntu3.3 amd64 [installed,automatic]
libguestfs-tools/bionic-updates,now 1:1.36.13-1ubuntu3.3 amd64 [installed]
libguestfs0/bionic-updates,now 1:1.36.13-1ubuntu3.3 amd64 [installed,automatic]
`

**Comment by vitalych** [comment]
How about this command?
```
$ apt-file search virt-win-reg
libguestfs-tools: /usr/bin/virt-win-reg
```

**Comment by LalaNguyen** [comment]
Here it is 
```
$apt-file search virt-win-reg
libguestfs-tools: /usr/bin/virt-win-reg
libguestfs-tools: /usr/share/bash-completion/completions/virt-win-reg
libguestfs-tools: /usr/share/man/ja/man1/virt-win-reg.1.gz
libguestfs-tools: /usr/share/man/man1/virt-win-reg.1.gz
libguestfs-tools: /usr/share/man/uk/man1/virt-win-reg.1.gz

```

**Comment by vitalych** [comment]
Ah, I misunderstood the error message. It complained that `/home/lala/s2e/images/.tmp-output/windows-10ent1703-x86_64/post_install_files/install_scripts/disable_windefend.reg` is missing. Maybe you did ctrl+c at some point before the file got copied, then restarted, and it didn't get copied. In any case, this could be fixed by changing these lines [1,2] to point to the guest-image source dir instead of the post-install folder.

[1] https://github.com/S2E/guest-images/blob/master/Makefile.windows#L257
[2] https://github.com/S2E/guest-images/blob/master/Makefile.windows#L262

**Comment by LalaNguyen** [comment]
Perhap you are right. Thank you very much for your helps! It is running smoothly now :+1:
