### ISSUE TITLE
Symbolic data content seed file problem

### ISSUE THREAD

**Issue by Pl0414141** [S2E/s2e-env#387]
Hi,

I can see in the official documentation (http://s2e.systems/docs/Tutorials/BasicLinuxSymbex/s2e.so.html#what-about-other-symbolic-input) the following:

# The @@ is a placeholder for a concrete file name that contains symbolic data
s2e new_project -i debian-9.2.1-i386 $S2EENV/images/debian-9.2.1-i386/guestfs/bin/cat @@

However, i would like that S2E use the content of my created seed file as **myvalidimagefile.png**

How can i do this?
Thanks

**Comment by vitalych** [comment]
Hi,

```
s2e new_project --use-seeds -i debian-9.2.1-i386 $S2EENV/images/debian-9.2.1-i386/guestfs/bin/cat @@
```

Place your seed files in the seeds folder and name them according to the format described here:
http://s2e.systems/docs/Tutorials/PoV/index.html?highlight=seed
<index>-<priority>.<extension>

**Comment by Pl0414141** [comment]
Hi,

i have created the project successfully and get running, the process has been running all night and is still running however i see an error in warnings.txt, repeated SeedSearcher messages in debug.txt and the CPU load is 0%.

1. Should I worry about the error that appears in the file 'warning.txt'?
2. The fact that the same SeedSearcher message appears again and again in the debug.txt file is normal?
3. How can I know if everything is going well?

root@xx-virtual-machine:~/fussea/projects/mybin/s2e-out-0# cat warnings.txt 
11 [State 2] HostFiles: could not open /home/xx/fussea/projects/mybin/seeds/4-4.png.symranges(errno 2)

root@xx-virtual-machine:~/fussea/projects/mybin/s2e-out-0# cat debug.txt
SeedScheduler: explorationState: 1 timeOfLastFetchedSeed: 29878 foundBlocks: 30071s foundCrashes: 30120s hpSeed: 29878s
SeedScheduler: idle detection: too many states
SeedSearcher: idle setting: idx=0 idle=0
SeedSearcher: Looking for new seeds
SeedSearcher: name: 1-1.png index:1 priority:1
SeedSearcher: name: 3-3.png index:3 priority:3
SeedSearcher: name: 2-2.png index:2 priority:2
SeedSearcher: name: 4-4.png index:4 priority:4
SeedSearcher: Fetched 4 valid seeds
SeedScheduler: explorationState: 1 timeOfLastFetchedSeed: 29880 foundBlocks: 30073s foundCrashes: 30122s hpSeed: 29880s
SeedScheduler: idle detection: too many states
SeedSearcher: idle setting: idx=0 idle=0
SeedSearcher: Looking for new seeds
SeedSearcher: name: 1-1.png index:1 priority:1
SeedSearcher: name: 3-3.png index:3 priority:3
SeedSearcher: name: 2-2.png index:2 priority:2
SeedSearcher: name: 4-4.png index:4 priority:4
SeedSearcher: Fetched 4 valid seeds
SeedScheduler: explorationState: 1 timeOfLastFetchedSeed: 29882 foundBlocks: 30075s foundCrashes: 30124s hpSeed: 29882s
SeedScheduler: idle detection: too many states
SeedSearcher: idle setting: idx=0 idle=0
SeedSearcher: Looking for new seeds
SeedSearcher: name: 1-1.png index:1 priority:1
SeedSearcher: name: 3-3.png index:3 priority:3
SeedSearcher: name: 2-2.png index:2 priority:2
SeedSearcher: name: 4-4.png index:4 priority:4
SeedSearcher: Fetched 4 valid seeds
SeedScheduler: explorationState: 1 timeOfLastFetchedSeed: 29884 foundBlocks: 30077s foundCrashes: 30126s hpSeed: 29884s
SeedScheduler: idle detection: too many states
SeedSearcher: idle setting: idx=0 idle=0
SeedSearcher: Looking for new seeds
SeedSearcher: name: 1-1.png index:1 priority:1
SeedSearcher: name: 3-3.png index:3 priority:3
SeedSearcher: name: 2-2.png index:2 priority:2
SeedSearcher: name: 4-4.png index:4 priority:4
SeedSearcher: Fetched 4 valid seeds
SeedScheduler: explorationState: 1 timeOfLastFetchedSeed: 29886 foundBlocks: 30079s foundCrashes: 30128s hpSeed: 29886s
SeedScheduler: idle detection: too many states
SeedSearcher: idle setting: idx=0 idle=0
SeedSearcher: Looking for new seeds
SeedSearcher: name: 1-1.png index:1 priority:1
SeedSearcher: name: 3-3.png index:3 priority:3
SeedSearcher: name: 2-2.png index:2 priority:2
SeedSearcher: name: 4-4.png index:4 priority:4
SeedSearcher: Fetched 4 valid seeds
SeedScheduler: explorationState: 1 timeOfLastFetchedSeed: 29888 foundBlocks: 30081s foundCrashes: 30130s hpSeed: 29888s
SeedScheduler: idle detection: too many states
SeedSearcher: idle setting: idx=0 idle=0
SeedSearcher: Looking for new seeds
SeedSearcher: name: 1-1.png index:1 priority:1
SeedSearcher: name: 3-3.png index:3 priority:3
SeedSearcher: name: 2-2.png index:2 priority:2
SeedSearcher: name: 4-4.png index:4 priority:4
SeedSearcher: Fetched 4 valid seeds

Thank you very much
