### ISSUE TITLE
HostFiles: could not open symranges (errno 2)

### ISSUE THREAD

**Issue by Pl0414141** [S2E/s2e-env#388]
Hi,

i have created the project successfully and get running, the process has been running all night and is still running however i see an error in warnings.txt, repeated SeedSearcher messages in debug.txt and the CPU load is 0%.

1. Should I worry about the error that appears in the file 'warning.txt'?
2. The fact that the same SeedSearcher message appears again and again in the debug.txt file is normal?
3. How can I know if everything is going well?

root@xx-virtual-machine:~/fussea/projects/mybin/s2e-out-0# cat warnings.txt 
11 [State 2] HostFiles: could not open /home/xx/fussea/projects/mybin/seeds/4-4.png.symranges(errno 2)

root@xx-virtual-machine:~/fussea/projects/mybin/s2e-out-0# cat debug.txt
SeedScheduler: explorationState: 1 timeOfLastFetchedSeed: 29878 foundBlocks: 30071s foundCrashes: 30120s hpSeed: 29878s
SeedScheduler: idle detection: too many states
SeedSearcher: idle setting: idx=0 idle=0
SeedSearcher: Looking for new seeds
SeedSearcher: name: 1-1.png index:1 priority:1
SeedSearcher: name: 3-3.png index:3 priority:3
SeedSearcher: name: 2-2.png index:2 priority:2
SeedSearcher: name: 4-4.png index:4 priority:4
SeedSearcher: Fetched 4 valid seeds
SeedScheduler: explorationState: 1 timeOfLastFetchedSeed: 29880 foundBlocks: 30073s foundCrashes: 30122s hpSeed: 29880s
SeedScheduler: idle detection: too many states
SeedSearcher: idle setting: idx=0 idle=0
SeedSearcher: Looking for new seeds
SeedSearcher: name: 1-1.png index:1 priority:1
SeedSearcher: name: 3-3.png index:3 priority:3
SeedSearcher: name: 2-2.png index:2 priority:2
SeedSearcher: name: 4-4.png index:4 priority:4
SeedSearcher: Fetched 4 valid seeds
SeedScheduler: explorationState: 1 timeOfLastFetchedSeed: 29882 foundBlocks: 30075s foundCrashes: 30124s hpSeed: 29882s
SeedScheduler: idle detection: too many states
SeedSearcher: idle setting: idx=0 idle=0
SeedSearcher: Looking for new seeds
SeedSearcher: name: 1-1.png index:1 priority:1
SeedSearcher: name: 3-3.png index:3 priority:3
SeedSearcher: name: 2-2.png index:2 priority:2
SeedSearcher: name: 4-4.png index:4 priority:4
SeedSearcher: Fetched 4 valid seeds
SeedScheduler: explorationState: 1 timeOfLastFetchedSeed: 29884 foundBlocks: 30077s foundCrashes: 30126s hpSeed: 29884s
SeedScheduler: idle detection: too many states
SeedSearcher: idle setting: idx=0 idle=0
SeedSearcher: Looking for new seeds
SeedSearcher: name: 1-1.png index:1 priority:1
SeedSearcher: name: 3-3.png index:3 priority:3
SeedSearcher: name: 2-2.png index:2 priority:2
SeedSearcher: name: 4-4.png index:4 priority:4
SeedSearcher: Fetched 4 valid seeds
SeedScheduler: explorationState: 1 timeOfLastFetchedSeed: 29886 foundBlocks: 30079s foundCrashes: 30128s hpSeed: 29886s
SeedScheduler: idle detection: too many states
SeedSearcher: idle setting: idx=0 idle=0
SeedSearcher: Looking for new seeds
SeedSearcher: name: 1-1.png index:1 priority:1
SeedSearcher: name: 3-3.png index:3 priority:3
SeedSearcher: name: 2-2.png index:2 priority:2
SeedSearcher: name: 4-4.png index:4 priority:4
SeedSearcher: Fetched 4 valid seeds
SeedScheduler: explorationState: 1 timeOfLastFetchedSeed: 29888 foundBlocks: 30081s foundCrashes: 30130s hpSeed: 29888s
SeedScheduler: idle detection: too many states
SeedSearcher: idle setting: idx=0 idle=0
SeedSearcher: Looking for new seeds
SeedSearcher: name: 1-1.png index:1 priority:1
SeedSearcher: name: 3-3.png index:3 priority:3
SeedSearcher: name: 2-2.png index:2 priority:2
SeedSearcher: name: 4-4.png index:4 priority:4
SeedSearcher: Fetched 4 valid seeds

Thank you very much

_Originally posted by @Pl0414141 in https://github.com/S2E/s2e-env/issues/387#issuecomment-591275029_

**Comment by vitalych** [comment]
It's better if you export the project and attach it here.
The warning is fine. The file it mentions is optional, it lets you specify which part of the file should be symbolic.
Note that state 0 will run forever, because it has to wait for new seeds to arrive.
You can check in debug.txt how many states have been forked. There should be at least one for each seed plus one that will run the binary without seeds.
