### ISSUE TITLE
NULL pointer deference in S2EExecutionState::addressSpaceChange

### ISSUE THREAD

**Issue by CvvT** [S2E/s2e-env#389]
Hi,

I got a segmentation fault on the following path:

klee::AddressSpace::unbindObject
klee::AddressSpace::addressSpaceChange
s2e::S2EExecutionState::addressSpaceChange
boost::intrusive_ptr<klee::ObjectState>::operator->
Assertion `px != 0' failed.

At this [line](https://github.com/S2E/s2e/blob/master/klee/lib/Core/AddressSpace.cpp#L43), it passes a null pointer as the third argument and then there is a dereference of the pointer without a check inside the function s2e::S2EExecutionState::addressSpaceChange.

I uploaded the project to google drive as github does not accept tar.xz file.
[attachment](https://drive.google.com/file/d/121nmHJLIumne278XQRpfp24cvObgSLbq/view?usp=sharing)

Thanks,
Weiteng

**Comment by CvvT** [comment]
FYI, the source code of the binary is available at git://sourceware.org/git/binutils-gdb.git

**Comment by vitalych** [comment]
I managed to reproduce it. Note that your project has an older structure (no guest-tools32 and guest-tools64 symlinks), you may want to upgrade it.

**Comment by vitalych** [comment]
You can comment out the assert, it should work. I'd still have to write a test for this though.

**Comment by CvvT** [comment]
I have tried this, but then it triggers another null pointer deference in this [function](https://github.com/S2E/s2e/blob/master/libs2ecore/src/S2EExecutionStateTlb.cpp#L69).

**Comment by vitalych** [comment]
I have a preliminary fix here: https://github.com/S2E/s2e/pull/10
