### ISSUE TITLE
"custom memory allocation vtable not supported"

### ISSUE THREAD

**Issue by bannsec** [S2E/s2e-env#39]
So, I've managed to get this at least somewhat installed. Performed the following steps:

1. Setup a new Ubuntu:16.04 docker image
1. s2e init command
1. s2e build command
1. s2e image_build -d command
1. s2e new_project --image debian-8.7.1-x86_64 /bin/ls

However, when I perform the following command:

1. s2e run ls

The TUI pops open for a second, then goes away. I've found some error logs in the project directory:

```
$ cat stderr.txt 

(process:837): GLib-WARNING **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmem.c:483: custom memory allocation vtable not supported
qemu-system-x86_64: -n: invalid option
```

```
$ cat warnings.txt
WARNING: Cannot get configuration value 'pluginsConfig['TestCaseGenerator'].logLevel':
    value of type nil can not be converted to string
WARNING: Cannot get configuration value 'pluginsConfig['ProcessExecutionDetector'].logLevel':
    value of type nil can not be converted to string

WARNING: Cannot get configuration value 'pluginsConfig['ModuleExecutionDetector'].logLevel':
    value of type nil can not be converted to string

WARNING: Cannot get configuration value 'pluginsConfig['ModuleExecutionDetector'].trackAllModules':
    value of type nil can not be converted to boolean

WARNING: Cannot get configuration value 'pluginsConfig['ModuleExecutionDetector'].configureAllModules':
    value of type nil can not be converted to boolean

WARNING: Cannot get configuration value 'pluginsConfig['ModuleExecutionDetector'].trackExecution':
    value of type nil can not be converted to boolean

WARNING: Cannot get configuration value 'pluginsConfig['StaticFunctionModels'].logLevel':
    value of type nil can not be converted to string

WARNING: Cannot get configuration value 'pluginsConfig['StaticFunctionModels'].count':
    value of type nil can not be converted to integer

WARNING: Cannot get configuration value 'pluginsConfig['CUPASearcher'].batchTime':
    value of type nil can not be converted to integer

WARNING: Cannot get configuration value 'pluginsConfig['CUPASearcher'].enabled':
    value of type nil can not be converted to boolean

WARNING: Cannot get configuration value 'pluginsConfig['TranslationBlockCoverage'].logLevel':
    value of type nil can not be converted to string

WARNING: Cannot get configuration value 'pluginsConfig['ModuleTracer'].logLevel':
    [string "return pluginsConfig['ModuleTracer'].logLevel..."]:1: attempt to index field 'ModuleTracer' (a nil value)

WARNING: Cannot get configuration value 'pluginsConfig['CorePlugin'].logLevel':
    [string "return pluginsConfig['CorePlugin'].logLevel"]:1: attempt to index field 'CorePlugin' (a nil value)

3 [State 0] LinuxMonitor: Module load not yet implemented
3 [State 0] LinuxMonitor: Module load not yet implemented
3 [State 0] LinuxMonitor: Module load not yet implemented
3 [State 0] LinuxMonitor: Module load not yet implemented
3 [State 0] LinuxMonitor: Module load not yet implemented
3 [State 0] LinuxMonitor: Module load not yet implemented
3 [State 0] LinuxMonitor: Module load not yet implemented
3 [State 0] LinuxMonitor: Module load not yet implemented
3 [State 0] LinuxMonitor: Module load not yet implemented
3 [State 0] LinuxMonitor: Module load not yet implemented
3 [State 0] BaseInstructions: Message from guest (0x7f14aa34ad36): S2E_SYM_ARGS is not set. All arguments will be concrete
All states were terminated
Terminating node 0 (instance slot 0)
```

Also this:

```
BEGIN searcher description
DFSSearcher
END searcher description
1 [State 0] Created initial state
Adding CPU (addr = 0x7fa7a6c8c010, size = 0x36e70)
Initializing periodic timer
Adding memory block (startAddr = 0xffffffffffffffff, size = 0x10000000, hostAddr = 0x7fa773e00000, isSharedConcrete=0, name=pc.ram)
Adding memory block (startAddr = 0xffffffffffffffff, size = 0x20000, hostAddr = 0x55bf72f39000, isSharedConcrete=1, name=pc.bios)
Adding memory block (startAddr = 0xffffffffffffffff, size = 0x20000, hostAddr = 0x55bf72f8a000, isSharedConcrete=1, name=pc.rom)
Adding memory block (startAddr = 0xffffffffffffffff, size = 0x800000, hostAddr = 0x7fa764200000, isSharedConcrete=1, name=vga.vram)
Adding memory block (startAddr = 0xffffffffffffffff, size = 0x10000, hostAddr = 0x55bf73a27000, isSharedConcrete=1, name=cirrus_vga.rom)
Adding memory block (startAddr = 0xffffffffffffffff, size = 0x20000, hostAddr = 0x55bf73a95000, isSharedConcrete=1, name=e1000.rom)
Warning: vlan 0 is not connected to host network
Could not initialize SDL(No available video device) - exiting
Terminating node 0 (instance slot 0)
```

**Comment by adrianherrera** [comment]
Where is the "also this" from? Debug.txt?

I never use `s2e run` personally. It is a bit experimental and really only useful for CGC binaries. I would just use `launch-s2e.sh` directly.

Ignore the vtable thing - it's just a warning. I'll look into that "-n: Invalid option" message though - that's interesting. Likewise the "SDL - exiting" message doesn't look good. I'll look into that too.

That all said, you have created a project to run `ls`. You have not specified any symbolic data (either as a file or command-line arg). So S2E will simply execute ls as is and execute immediately anyway.

**Comment by adrianherrera** [comment]
BTW can I suggest that we move this to the S2E dev google groups at https://groups.google.com/forum/#!forum/s2e-dev? You can just create the one topic there and update it with issues as you go along, and we can discuss things there. Creating all these issues is not making things easier.

Thanks!

**Comment by adrianherrera** [comment]
I just tried `s2e run` and I did not get the `-n: invalid option` or the `SDL - exiting` message. Have you modified anything?

**Comment by Owlz** [comment]
Nope. This is about as clean of an install as they come. Literally building from the Ubuntu:16.04 docker image directly.

**Comment by adrianherrera** [comment]
Hmm okay. I even followed the exact same steps as you and created a new project for `/bin/ls`. Cannot reproduce those messages. However, the quick termination is expected because there is no symbolic execution.

**Comment by Owlz** [comment]
Tried changing bootstrap to the following, still quick exit:

```bash
execute "S2E_SYM_ARGS=\"1 2\" ./ls hello"
```

**Comment by adrianherrera** [comment]
No that is not correct.

`S2E_SYM_ARGS` is an environment variable and should be set in the `execute_target` function in the bootstrap script. Just grep for `S2E_SYM_ARGS` in the bootstrap script and you will find it in a comment. Instructions are given in https://github.com/S2E/docs/blob/master/src/Howtos/s2e.so.rst

However just stop for a second and have a think about what you are trying to do. Does performing `ls` on a symbolic string have any meaning? What are you trying to achieve here?

**Comment by Owlz** [comment]
Honestly just trying to get it to run on something in general :-) Supposedly there could be parsing bugs in how ls handles its arguments. But really, just trying to get S2E to run and understand it's output/how to use it.

**Comment by Owlz** [comment]
side note: it seems strange that `execute_target` has this command:

```bash
./${TARGET}
```

While at the bottom this is run:
```
execute "./ls"
```

Would actually end up executing "././ls". While that's valid, if one wants to run an absolute path (such as /bin/ls) instead, the `execute_target` use of "./" would force the path to be relative.

**Comment by Owlz** [comment]
Edited `execute_target` to be the following:

```bash
LD_PRELOAD=./s2e.so S2E_SYM_ARGS="1" ./${TARGET}  > /dev/null 2> /dev/null
```

Still insta-exit.

**Comment by Owlz** [comment]
also side note, it is non-intuitive for me as to where to place the S2E_SYM_ARGS. A nice feature would be to have that argument in there by default, and simply provide the variable definition at the top or in some other config. That way, all one would have to do is change the config, rather than editing bash code directly.

**Comment by adrianherrera** [comment]
I suggest starting with the tutorials first (cat and CGC).

Yes, the relative path is intentional because when you create a project in s2e-env, the target binary exists on your host and gets uploaded to the S2E VM by the bootstrap script. Since the target binary is the one that gets uploaded, you don't want it getting confused with the `/bin/ls` that exists in the VM (it may be slightly different).

If you want to target a binary that already exists in the VM, you will have to do this manually. s2e-env does not currently support this.

The insta-exit is because you have still not specified any arguments to `ls`.  Yes, you have specified that you want to make the first argument symbolic, however you have not specified any arguments to make symbolic.

**Comment by Owlz** [comment]
Sorry, i was unclear. I also changed to the following:

```bash
execute "./ls hello"
```

Assuming that's what you're referring to.

**Comment by adrianherrera** [comment]
There already exists comments in the bootstrap script that tell you where to add the S2E_SYM_ARGS environment variable. However, it probably does make sense to have it in there by default and just set it to "". I will do this.

**Comment by adrianherrera** [comment]
No that is not correct. You add the argument on the same line where ${TARGET} is executed. So it would be:

`S2E_SYM_ARGS="1" LD_PRELOAD="s2e.so" ./${TARGET} hello > /dev/null 2> /dev/null`

When you create the project you can also create it with `s2e new_project ls hello` and it will add the "hello" argument into the bootstrap script for you. This is what's done in the cat tutorial. However it is still up to you to set the argument to symbolic.

**Comment by Owlz** [comment]
Ok. Changed it as you mentioned and it still exits immediately. I'll try running through the cat tutorial and see if that works.

**Comment by adrianherrera** [comment]
Ok sounds good. Sorry, I'm not sure why it's exiting immediately for you.

**Comment by vitalych** [comment]
Can this be closed?

**Comment by bannsec** [comment]
I would presume so. I have since gotten S2E to run properly (other submitted issues aside).

**Comment by swq499809608** [comment]
解决办法:
    yum –y install  gperftools-libs
重启系统
[root@l2 154363a6-13e0-4570-a1ef-53f2becacfbd]# rpm -ql gperftools-libs 
/usr/lib64/libprofiler.so.0
/usr/lib64/libprofiler.so.0.4.5
/usr/lib64/libtcmalloc.so.4
/usr/lib64/libtcmalloc.so.4.2.6
/usr/lib64/libtcmalloc_and_profiler.so.4
/usr/lib64/libtcmalloc_and_profiler.so.4.2.6
/usr/lib64/libtcmalloc_debug.so.4
/usr/lib64/libtcmalloc_debug.so.4.2.6
/usr/lib64/libtcmalloc_minimal.so.4
/usr/lib64/libtcmalloc_minimal.so.4.2.6
/usr/lib64/libtcmalloc_minimal_debug.so.4
/usr/lib64/libtcmalloc_minimal_debug.so.4.2.6
