### ISSUE TITLE
"Too many bits for uint64_t"' failed.

### ISSUE THREAD

**Issue by CvvT** [S2E/s2e-env#400]
Hi,

I encountered the following assertion error:
s2e/build/llvm-9.0.0.src/include/llvm/ADT/APInt.h:1565: uint64_t llvm::APInt::getZExtValue() const: Assertion `getActiveBits() <= 64 && "Too many bits for uint64_t"' failed. 

The backtrace is the following:
4  0x000015555230c93e in llvm::APInt::getZExtValue (
    this=0x15545b8bc060)
    at /home/wchen130/workplace/fuzz/s2e/build/llvm-9.0.0.src/include/llvm/ADT/APInt.h:1565
5  0x000015555231282e in klee::ConstantExpr::getZExtValue (
    this=0x15545b8bc050, bits=128)
    at /home/wchen130/workplace/fuzz/s2e/source/s2e/klee/include/klee/Expr.h:436
6  0x000015555280c2f4 in klee::BitfieldSimplifier::replaceWithConstant(klee::ref<klee::Expr> const&, unsigned __int128) (
    this=0x1555552cbcd0 <klee::ExecutionState::s_simplifier>,
    e=..., value=340282366920938463454735052906065231221)
    at /home/wchen130/workplace/fuzz/s2e/source/s2e/klee/lib/Expr/BitfieldSimplifier.cpp:90
7  0x000015555280ec25 in klee::BitfieldSimplifier::doSimplifyBits(klee::ref<klee::Expr> const&, unsigned __int128) (
    this=0x1555552cbcd0 <klee::ExecutionState::s_simplifier>,
    e=..., ignoredBits=0)
    at /home/wchen130/workplace/fuzz/s2e/source/s2e/klee/lib/Expr/BitfieldSimplifier.cpp:342
8  0x000015555280f393 in klee::BitfieldSimplifier::simplify (
    this=0x1555552cbcd0 <klee::ExecutionState::s_simplifier>,
    e=..., knownZeroBits=0x0)
    at /home/wchen130/workplace/fuzz/s2e/source/s2e/klee/lib/Expr/BitfieldSimplifier.cpp:395
9  0x000015555274fa45 in klee::ExecutionState::simplifyExpr (
    this=0x15545adb5d30, e=...)
    at /home/wchen130/workplace/fuzz/s2e/source/s2e/klee/lib/Core/ExecutionState.cpp:454

Thanks,
Weiteng

**Comment by vitalych** [comment]
Related to https://github.com/S2E/s2e-env/issues/348

**Comment by CvvT** [comment]
Any progress on the fix? It's been under review for a long time. Without the fix, I thought S2E can already handle values of 128 bits, can't it?

**Comment by vitalych** [comment]
Nope, there were some comments left unaddressed by the original author and then the issue went stale. If you have some time, please rebase it. I don't have much time on my side to do it, I'll get to it if I run into the bug personally.

**Comment by vitalych** [comment]
it would help if you could provide a test case.
