### ISSUE TITLE
Where is s2e.ko?

### ISSUE THREAD

**Issue by LalaNguyen** [S2E/s2e-env#407]
Hi, I am planning to analyze syscall-related bugs in Linux kernel using fault injection approach. Basically, I want to replicate s2e.sys's functionality in the windows to [s2e.ko](http://s2e.systems/docs/Tutorials/PoV/index.html) in the Linux. When a syscall handler invokes kernel functions, I will treat the kernel functions as black box and return the error codes to the syscall handler.

However, I could not have found the code part that is related to s2e.ko. The reason why I need the s2e.ko is because I can write wrapper kernel functions with it and s2e.ko can inform the S2E core the addresses of kernel functions, similar to s2e.sys.

Thank for your helps in advance !

Minh

**Comment by vitalych** [comment]
It is located here: https://github.com/S2E/s2e-linux-kernel/blob/fab6b51b27e133333d5ca402b5f108ab6839d8db/linux-4.9.3/kernel/s2e/s2e.c
It's built into the kernel, so there is no separate s2e.ko.

You can of course modify it, but you'd have to rebuild the kernel and the vm image everytime, which is not practical. Instead, you should write an out-of-tree kernel module, build it on the host in a docker container, then upload it into the guest vm with s2eget.

You can find instructions on how to build a Linux kernel module for S2E here: http://s2e.systems/docs/Tutorials/SystemTap/index.html
You only need the part about installing the kernel headers and building modules.

**Comment by LalaNguyen** [comment]
Hi Vitaly,

Thanks so much for the pointer !
