### ISSUE TITLE
How does S2E map dynamically allocated memory into Klee?

### ISSUE THREAD

**Issue by jinjing750629** [S2E/s2e-env#418]
Dear Sir,

I want to understand more about how S2E maps a malloced memory region into a Klee ObjectState. I saw there are quite a lot addExternaObject in the source code which explicitly maps S2E global variables into Klee, such as cpu env, g_s2e. But if I dynamically allocate a  memory region inside my progam under investigation, how does this portion of memory get mapped?

Thanks

**Comment by vitalych** [comment]
S2E operates with physical memory. The KLEE object states that you mention store memory pages + some internal S2E variables. The guest is not aware that it runs on S2E, if you call malloc() in your program, it will be mapped by the OS into some physical memory pages. Read/writes to physical memory is redirected by S2E/KLEE to the appropriate object states.

**Comment by jinjing750629** [comment]
I guess there are many object states. Are they created automatically when program calls malloc? Where can I find the related source code which is in charge of object state lifetime? 

Thanks

**Comment by vitalych** [comment]
These object states are created when S2E starts. S2E doesn't know if a program calls malloc or not, all its sees is a stream of x86 instructions.
S2E registers memory blocks here: https://github.com/S2E/s2e/blob/master/libs2ecore/src/S2EExecutor.cpp#L559
These blocks are set up by QEMU when it initializes guest physical memory.
