### ISSUE TITLE
Parallel S2E Not Working

### ISSUE THREAD

**Issue by Owlz** [S2E/s2e-env#42]
So I'm attempting to follow these instructions: https://github.com/S2E/docs/blob/master/src/Howtos/Parallel.rst

I set the `S2E_MAX_PROCESSES` variable to 8 in my case in the launcher.sh script for the project. Then, I have tried both running the launcher script as well as using s2e run. Neither end up using more than a single core.

A side note as well, when I use the s2e run command, it appears to just get stuck at "Waiting for analysis". I have yet to get past that point.

I am still getting a bunch of warnings like this in "warnings.txt" file

```
WARNING: Cannot get configuration value 'pluginsConfig['LinuxMonitor'].terminateOnSegfault':
    value of type nil can not be converted to boolean

WARNING: Cannot get configuration value 'pluginsConfig['ProcessExecutionDetector'].logLevel':
    value of type nil can not be converted to string

WARNING: Cannot get configuration value 'pluginsConfig['ModuleExecutionDetector'].logLevel':
    value of type nil can not be converted to string

WARNING: Cannot get configuration value 'pluginsConfig['ModuleExecutionDetector'].trackAllModules':
    value of type nil can not be converted to boolean

WARNING: Cannot get configuration value 'pluginsConfig['ModuleExecutionDetector'].configureAllModules':
    value of type nil can not be converted to boolean

WARNING: Cannot get configuration value 'pluginsConfig['ModuleExecutionDetector'].trackExecution':
    value of type nil can not be converted to boolean

WARNING: Cannot get configuration value 'pluginsConfig['StaticFunctionModels'].logLevel':
    value of type nil can not be converted to string

WARNING: Cannot get configuration value 'pluginsConfig['StaticFunctionModels'].count':
    value of type nil can not be converted to integer

WARNING: Cannot get configuration value 'pluginsConfig['CUPASearcher'].batchTime':
    value of type nil can not be converted to integer

WARNING: Cannot get configuration value 'pluginsConfig['CUPASearcher'].enabled':
    value of type nil can not be converted to boolean

WARNING: Cannot get configuration value 'pluginsConfig['TranslationBlockCoverage'].logLevel':
    value of type nil can not be converted to string

WARNING: Cannot get configuration value 'pluginsConfig['ModuleTracer'].logLevel':
    [string "return pluginsConfig['ModuleTracer'].logLevel..."]:1: attempt to index field 'ModuleTracer' (a nil value)

WARNING: Cannot get configuration value 'pluginsConfig['CorePlugin'].logLevel':
    [string "return pluginsConfig['CorePlugin'].logLevel"]:1: attempt to index field 'CorePlugin' (a nil value)
```

**Comment by Epeius** [comment]
You can just ignore these warnings. In order to use parallel mode, please make sure you are going to run s2e in symbolic mode. More s2e processes will be forked only if there are more than one states in the system.

-Bin

**Comment by Epeius** [comment]
BTW, as Adrian mentioned before, we highly recommend to use launch script rather than the tui mode.

**Comment by adrianherrera** [comment]
Hi Owlz,

As previously mentioned, those warnings are related to plugins and nothing to do with multi-process mode. Ignore them.

What are you trying to run? Did you get symbolic data working? If not, then no new states will fork and hence no new processes will be generated.

`s2e run` does not use the `launch-s2e.sh` script - they are totally independent. So setting `S2E_MAX_PROCESS` in the launch script will do nothing for `s2e run`.

~Adrian

**Comment by Owlz** [comment]
Hey guys, so i've gotten the `./launch-s2e.sh` to work with multi-processing. I'm not really attempting to use the tui anymore. Think this can probably be closed.

**Comment by adrianherrera** [comment]
Nice, thanks :)
