### ISSUE TITLE
Store windows updates on github

### ISSUE THREAD

**Issue by pokamolodoy406** [S2E/s2e-env#424]
Hello. I build image of Windows 7. 
I got an error. 
Error related to updates of Windows. 
<img width="401" alt="error_try_true" src="https://user-images.githubusercontent.com/37054694/99882114-376e6980-2c2f-11eb-99b4-d4c035853d3e.png">
<img width="409" alt="error_updates_two" src="https://user-images.githubusercontent.com/37054694/99882149-68e73500-2c2f-11eb-9e6f-ae37740cc7c5.png">

How I can disable updates for image of Windows 7 ?)

**Comment by vitalych** [comment]
You can't. It would be a nice feature to add. I renamed the issue accordingly.
For now, you can try to figure out why the patches don't download. That particular one is downloaded here:
https://github.com/S2E/guest-images/blob/master/Makefile.windows.updates32#L19
It looks like it has been replaced by a more recent one:
https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=7170fb56-a41c-4a45-a5b2-92e4961935cf

So I suggest you remove it and add the updated patch instead:
- Remove this section: https://github.com/S2E/guest-images/blob/master/Windows/Windows_7_SP1_Updates_x86.ul#L26
- Add a new entry after this one: https://github.com/S2E/guest-images/blob/master/Windows/Windows_7_SP1_Updates_x86.ul#L65
- Make sure that the entry has the correct date, updates are installed chronologically.
You can download / get the URLs for the patches here: https://www.catalog.update.microsoft.com/Search.aspx?q=KB4580970
- Regenerate the updates by running the command here: https://github.com/S2E/guest-images/blob/master/Makefile.windows.updates32#L2
- Send a pull request once it works.

**Comment by vitalych** [comment]
Renamed the title of the issue, as the actual problem is to make it more reliable to download updates.

**Comment by vitalych** [comment]
@pokamolodoy406 I updated the URLs, so downloading them should work ok now.

**Comment by jskim20210115** [comment]
@vitalych 
Hi, Can I disable update steps when I build windows 10 images?
Thank you!

**Comment by vitalych** [comment]
You could disable them, but it would require commenting out a number of things in the scripts. What's the problem by the way? Do they fail to install?

**Comment by jskim20210115** [comment]
Got some 404 errors while downloading the files listed in the scripts.
Maybe some of them are outdated?

**Comment by vitalych** [comment]
Microsoft probably removed them. I dumped an archive of the updates here: 

https://github.com/S2E/guest-images/releases/download/v2.0.0/win7_updates_x64.tar.gz
https://github.com/S2E/guest-images/releases/download/v2.0.0/win7_updates_x86.tar.gz

Unzip them in the `$ENV/images/.tmp-output/win_apps/win7_updates/` folder.

**Comment by jskim20210115** [comment]
Thank you. Let me try it.
