### ISSUE TITLE
s2e keeps switching states back and forth

### ISSUE THREAD

**Issue by jinjing750629** [S2E/s2e-env#425]
Vitaly, I am fuzzing ans.1 decoder these days. S2E keeps switching states back and forth without generating any useful test cases. I set up use-dfs-search=true to klee, but it doesn't work. I assume there maybe a dead loop embedded inside the symbolic execution path. I saw S2E has several loop plugins but I haven't ideas how to use them. Would you please give me some instructions how to debug this issue? 
Thanks

Following is the log generated by S2E

1454 [State 43] Switching from state 43 to state 47
1459 [State 47] Switching from state 47 to state 22
1464 [State 22] Switching from state 22 to state 24
1474 [State 24] Switching from state 24 to state 22
1479 [State 22] Switching from state 22 to state 10
1484 [State 10] Switching from state 10 to state 45
1489 [State 45] Switching from state 45 to state 8
1494 [State 8] Switching from state 8 to state 22
1499 [State 22] Switching from state 22 to state 45
1504 [State 45] Switching from state 45 to state 43
1509 [State 43] Switching from state 43 to state 47
1514 [State 47] Switching from state 47 to state 45
1519 [State 45] Switching from state 45 to state 9
1524 [State 9] Switching from state 9 to state 24
1529 [State 24] Switching from state 24 to state 3
1534 [State 3] Switching from state 3 to state 8
1539 [State 8] Switching from state 8 to state 9
1544 [State 9] Switching from state 9 to state 80
1549 [State 80] Switching from state 80 to state 46
1554 [State 46] Switching from state 46 to state 3
1559 [State 3] Switching from state 3 to state 8
1564 [State 8] Switching from state 8 to state 23
1569 [State 23] Switching from state 23 to state 45
1574 [State 45] Switching from state 45 to state 23
1579 [State 23] Switching from state 23 to state 47
1584 [State 47] Switching from state 47 to state 46
1589 [State 46] Switching from state 46 to state 80
1599 [State 80] Switching from state 80 to state 46
1604 [State 46] Switching from state 46 to state 24
1609 [State 24] Switching from state 24 to state 8
1614 [State 8] Switching from state 8 to state 22
1619 [State 22] Switching from state 22 to state 43
1624 [State 43] Switching from state 43 to state 10
1629 [State 10] Switching from state 10 to state 80
1634 [State 80] Switching from state 80 to state 24
1639 [State 24] Switching from state 24 to state 43
1644 [State 43] Switching from state 43 to state 45
1655 [State 45] Switching from state 45 to state 24
1660 [State 24] Switching from state 24 to state 23
1665 [State 23] Switching from state 23 to state 22
1670 [State 22] Switching from state 22 to state 45
1675 [State 45] Switching from state 45 to state 22
1680 [State 22] Switching from state 22 to state 23
1685 [State 23] Switching from state 23 to state 3
1700 [State 3] Switching from state 3 to state 58
1705 [State 58] Switching from state 58 to state 20
1710 [State 20] Switching from state 20 to state 10
1715 [State 10] Switching from state 10 to state 8
1720 [State 8] Switching from state 8 to state 23
1727 [State 23] Switching from state 23 to state 45
1732 [State 45] Switching from state 45 to state 47
1737 [State 47] Switching from state 47 to state 46
1742 [State 46] Switching from state 46 to state 8
1747 [State 8] Switching from state 8 to state 9
1752 [State 9] Switching from state 9 to state 46
1757 [State 46] Switching from state 46 to state 8
1762 [State 8] Switching from state 8 to state 24
1767 [State 24] Switching from state 24 to state 8
1772 [State 8] Switching from state 8 to state 80
1777 [State 80] Switching from state 80 to state 43
1782 [State 43] Switching from state 43 to state 9
1787 [State 9] Switching from state 9 to state 58
1792 [State 58] Switching from state 58 to state 45
1797 [State 45] Switching from state 45 to state 10
1802 [State 10] Switching from state 10 to state 22
1807 [State 22] Switching from state 22 to state 58
1812 [State 58] Switching from state 58 to state 23
1824 [State 23] Switching from state 23 to state 24
1829 [State 24] Switching from state 24 to state 47
1834 [State 47] Switching from state 47 to state 10
1839 [State 10] Switching from state 10 to state 46
1849 [State 46] Switching from state 46 to state 10
1854 [State 10] Switching from state 10 to state 20
1859 [State 20] Switching from state 20 to state 43
1864 [State 43] Switching from state 43 to state 9
1869 [State 9] Switching from state 9 to state 58
1874 [State 58] Switching from state 58 to state 46
1879 [State 46] Switching from state 46 to state 43
1884 [State 43] Switching from state 43 to state 24
1894 [State 24] Switching from state 24 to state 46
1899 [State 46] Switching from state 46 to state 20
1904 [State 20] Switching from state 20 to state 9
1909 [State 9] Switching from state 9 to state 10
1914 [State 10] Switching from state 10 to state 58
1919 [State 58] Switching from state 58 to state 22
1924 [State 22] Switching from state 22 to state 24
1929 [State 24] Switching from state 24 to state 3
1934 [State 3] Switching from state 3 to state 23
1939 [State 23] Switching from state 23 to state 10
1944 [State 10] Switching from state 10 to state 46
1949 [State 46] Switching from state 46 to state 23
1954 [State 23] Switching from state 23 to state 80
1959 [State 80] Switching from state 80 to state 23
1974 [State 23] Switching from state 23 to state 10
1979 [State 10] Switching from state 10 to state 46
1984 [State 46] Switching from state 46 to state 22
1989 [State 22] Switching from state 22 to state 47
1994 [State 47] Switching from state 47 to state 24
1999 [State 24] Switching from state 24 to state 47
2004 [State 47] Switching from state 47 to state 80
2009 [State 80] Switching from state 80 to state 9
2014 [State 9] Switching from state 9 to state 24
2019 [State 24] Switching from state 24 to state 9
2024 [State 9] Switching from state 9 to state 80
2029 [State 80] Switching from state 80 to state 58
2034 [State 58] Switching from state 58 to state 47
2039 [State 47] Switching from state 47 to state 24
2044 [State 24] Switching from state 24 to state 22
2049 [State 22] Switching from state 22 to state 9
2054 [State 9] Switching from state 9 to state 43
2059 [State 43] Switching from state 43 to state 47
2064 [State 47] Switching from state 47 to state 3
2069 [State 3] Switching from state 3 to state 46
2074 [State 46] Switching from state 46 to state 3
2084 [State 3] Switching from state 3 to state 45
2089 [State 45] Switching from state 45 to state 80
2094 [State 80] Switching from state 80 to state 8
2099 [State 8] Switching from state 8 to state 47
2104 [State 47] Switching from state 47 to state 24
2109 [State 24] Switching from state 24 to state 20
2114 [State 20] Switching from state 20 to state 10
2119 [State 10] Switching from state 10 to state 20
2124 [State 20] Switching from state 20 to state 23
2129 [State 23] Switching from state 23 to state 43
2135 [State 43] Switching from state 43 to state 47
2140 [State 47] Switching from state 47 to state 46
2145 [State 46] Switching from state 46 to state 8
2150 [State 8] Switching from state 8 to state 23
2155 [State 23] Switching from state 23 to state 80
2160 [State 80] Switching from state 80 to state 45
2165 [State 45] Switching from state 45 to state 43
2170 [State 43] Switching from state 43 to state 9
2175 [State 9] Switching from state 9 to state 80
2180 [State 80] Switching from state 80 to state 43
2185 [State 43] Switching from state 43 to state 23
2190 [State 23] Switching from state 23 to state 45
2195 [State 45] Switching from state 45 to state 43
2205 [State 43] Switching from state 43 to state 45
2215 [State 45] Switching from state 45 to state 9
2220 [State 9] Switching from state 9 to state 23
2230 [State 23] Switching from state 23 to state 46
2235 [State 46] Switching from state 46 to state 22
2240 [State 22] Switching from state 22 to state 80
2245 [State 80] Switching from state 80 to state 58
2250 [State 58] Switching from state 58 to state 23
2255 [State 23] Switching from state 23 to state 20
2260 [State 20] Switching from state 20 to state 43
2265 [State 43] Switching from state 43 to state 20
2270 [State 20] Switching from state 20 to state 80
2275 [State 80] Switching from state 80 to state 10
2280 [State 10] Switching from state 10 to state 3
2285 [State 3] Switching from state 3 to state 46
2290 [State 46] Switching from state 46 to state 23
2295 [State 23] Switching from state 23 to state 58
2300 [State 58] Switching from state 58 to state 22
2305 [State 22] Switching from state 22 to state 58
2310 [State 58] Switching from state 58 to state 45
2315 [State 45] Switching from state 45 to state 43
2320 [State 43] Switching from state 43 to state 24
2325 [State 24] Switching from state 24 to state 22
2330 [State 22] Switching from state 22 to state 20
2335 [State 20] Switching from state 20 to state 23
2340 [State 23] Switching from state 23 to state 45
2345 [State 45] Switching from state 45 to state 8
2350 [State 8] Switching from state 8 to state 20
2355 [State 20] Switching from state 20 to state 9
2360 [State 9] Switching from state 9 to state 58
2365 [State 58] Switching from state 58 to state 43
2370 [State 43] Switching from state 43 to state 45
2375 [State 45] Switching from state 45 to state 9
2380 [State 9] Switching from state 9 to state 22
2385 [State 22] Switching from state 22 to state 46
2395 [State 46] Switching from state 46 to state 58
2400 [State 58] Switching from state 58 to state 46
2406 [State 46] Switching from state 46 to state 24
2416 [State 24] Switching from state 24 to state 10
2421 [State 10] Switching from state 10 to state 47
2426 [State 47] Switching from state 47 to state 22
2436 [State 22] Switching from state 22 to state 3
2441 [State 3] Switching from state 3 to state 45
2446 [State 45] Switching from state 45 to state 43
2451 [State 43] Switching from state 43 to state 9
2456 [State 9] Switching from state 9 to state 10
2461 [State 10] Switching from state 10 to state 8
2466 [State 8] Switching from state 8 to state 45
2471 [State 45] Switching from state 45 to state 3
2476 [State 3] Switching from state 3 to state 45
2481 [State 45] Switching from state 45 to state 10
2486 [State 10] Switching from state 10 to state 22
2491 [State 22] Switching from state 22 to state 23
2496 [State 23] Switching from state 23 to state 46
2501 [State 46] Switching from state 46 to state 20
2506 [State 20] Switching from state 20 to state 45
2516 [State 45] Switching from state 45 to state 3
2521 [State 3] Switching from state 3 to state 23
2526 [State 23] Switching from state 23 to state 43
2531 [State 43] Switching from state 43 to state 3
2536 [State 3] Switching from state 3 to state 20
2541 [State 20] Switching from state 20 to state 47
2546 [State 47] Switching from state 47 to state 45
2551 [State 45] Switching from state 45 to state 47
2556 [State 47] Switching from state 47 to state 43
2561 [State 43] Switching from state 43 to state 45
2566 [State 45] Switching from state 45 to state 24
2571 [State 24] Switching from state 24 to state 23
2576 [State 23] Switching from state 23 to state 24
2581 [State 24] Switching from state 24 to state 20
2586 [State 20] Switching from state 20 to state 43
2591 [State 43] Switching from state 43 to state 58
2596 [State 58] Switching from state 58 to state 46
2601 [State 46] Switching from state 46 to state 24
2606 [State 24] Switching from state 24 to state 20
2611 [State 20] Switching from state 20 to state 24
2616 [State 24] Switching from state 24 to state 43
2621 [State 43] Switching from state 43 to state 3
2626 [State 3] Switching from state 3 to state 10
2631 [State 10] Switching from state 10 to state 8
2636 [State 8] Switching from state 8 to state 80
2646 [State 80] Switching from state 80 to state 3
2651 [State 3] Switching from state 3 to state 80
2656 [State 80] Switching from state 80 to state 8
2661 [State 8] Switching from state 8 to state 9
2666 [State 9] Switching from state 9 to state 20
2671 [State 20] Switching from state 20 to state 22
2676 [State 22] Switching from state 22 to state 10
2681 [State 10] Switching from state 10 to state 45
2686 [State 45] Switching from state 45 to state 46
2696 [State 46] Switching from state 46 to state 22
2701 [State 22] Switching from state 22 to state 58
2706 [State 58] Switching from state 58 to state 46
2711 [State 46] Switching from state 46 to state 22
2716 [State 22] Switching from state 22 to state 9
2721 [State 9] Switching from state 9 to state 10
2726 [State 10] Switching from state 10 to state 45
2731 [State 45] Switching from state 45 to state 22
2736 [State 22] Switching from state 22 to state 47
2741 [State 47] Switching from state 47 to state 58
2746 [State 58] Switching from state 58 to state 8
2751 [State 8] Switching from state 8 to state 23
2756 [State 23] Switching from state 23 to state 8
2761 [State 8] Switching from state 8 to state 10
2766 [State 10] Switching from state 10 to state 46
2771 [State 46] Switching from state 46 to state 10
2776 [State 10] Switching from state 10 to state 22
2782 [State 22] Switching from state 22 to state 80
2787 [State 80] Switching from state 80 to state 24
2792 [State 24] Switching from state 24 to state 80
2797 [State 80] Switching from state 80 to state 46
2807 [State 46] Switching from state 46 to state 10
2812 [State 10] Switching from state 10 to state 58
2817 [State 58] Switching from state 58 to state 8
2822 [State 8] Switching from state 8 to state 43
2827 [State 43] Switching from state 43 to state 47
2832 [State 47] Switching from state 47 to state 8
2837 [State 8] Switching from state 8 to state 24
2842 [State 24] Switching from state 24 to state 10
2847 [State 10] Switching from state 10 to state 58
2852 [State 58] Switching from state 58 to state 47
2857 [State 47] Switching from state 47 to state 45
2862 [State 45] Switching from state 45 to state 23
2867 [State 23] Switching from state 23 to state 24
2872 [State 24] Switching from state 24 to state 80
2877 [State 80] Switching from state 80 to state 45
2882 [State 45] Switching from state 45 to state 20
2887 [State 20] Switching from state 20 to state 3
2892 [State 3] Switching from state 3 to state 20
2897 [State 20] Switching from state 20 to state 23
2902 [State 23] Switching from state 23 to state 80
2907 [State 80] Switching from state 80 to state 20
2912 [State 20] Switching from state 20 to state 9
2917 [State 9] Switching from state 9 to state 23
2922 [State 23] Switching from state 23 to state 20
2927 [State 20] Switching from state 20 to state 47
2932 [State 47] Switching from state 47 to state 43
2937 [State 43] Switching from state 43 to state 45
2947 [State 45] Switching from state 45 to state 46
2952 [State 46] Switching from state 46 to state 80
2957 [State 80] Switching from state 80 to state 47
2962 [State 47] Switching from state 47 to state 8
2967 [State 8] Switching from state 8 to state 20
2972 [State 20] Switching from state 20 to state 23
2977 [State 23] Switching from state 23 to state 46
2982 [State 46] Switching from state 46 to state 43
2987 [State 43] Switching from state 43 to state 3
2997 [State 3] Switching from state 3 to state 45
3002 [State 45] Switching from state 45 to state 58
3007 [State 58] Switching from state 58 to state 10
3012 [State 10] Switching from state 10 to state 47
3017 [State 47] Switching from state 47 to state 46
3022 [State 46] Switching from state 46 to state 23
3027 [State 23] Switching from state 23 to state 46
3032 [State 46] Switching from state 46 to state 8
3037 [State 8] Switching from state 8 to state 3
3042 [State 3] Switching from state 3 to state 58
3047 [State 58] Switching from state 58 to state 47
3052 [State 47] Switching from state 47 to state 8
3057 [State 8] Switching from state 8 to state 80
3062 [State 80] Switching from state 80 to state 22
3067 [State 22] Switching from state 22 to state 3
3072 [State 3] Switching from state 3 to state 47

.......

**Comment by vitalych** [comment]
You cannot use KLEE searchers, you need to use an S2E plugin. It uses the CUPASearcher by default, which you can make behave like DFS by increasing the timeout before state switching to a large value.
https://github.com/S2E/s2e-env/blob/master/s2e_env/templates/s2e-config.lua#L267
