### ISSUE TITLE
Supported Instruction Sets

### ISSUE THREAD

**Issue by qinkunbao** [S2E/s2e-env#429]
Hi,

I was trying to use s2e to analyze some crypto libraries. However, the target program crashed because the qemu VM doesn't support SSE4.1. May I ask if you have a plan to support some relevantly new instruction sets? BTW, do you have a list of instruction sets that s2e supports?

**Comment by vitalych** [comment]
S2E currently supports instruction sets from QEMU 1.0.
Adding support for more is definitely an issue, but unfortunately I don't have an ETA.
Here is the issue: https://github.com/S2E/s2e-env/issues/269. It's more general, perhaps just limiting the upgrade to the specific instruction sets will be much easier.
