### ISSUE TITLE
revgen: undefined dwarf reference while linking

### ISSUE THREAD

**Issue by ZiwenWan** [S2E/s2e-env#437]
Hi,

Thanks for creating this amazing tool! I was trying to build via the command "s2e build". I met some linking issue when linking the target revgen32. 

Here is the log 

> make[3]: Entering directory '/apollo/s2e/build/tools-release'
> [ 88%] Linking CXX executable revgen32
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `~ElfDwarf':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:47: undefined reference to `dwarf_dealloc'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:51: undefined reference to `dwarf_finish'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::printDie(Dwarf_Die_s*)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:71: undefined reference to `dwarf_tag'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:72: undefined reference to `dwarf_get_TAG_name'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::printAttributes(Dwarf_Die_s*)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:87: undefined reference to `dwarf_attrlist'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:99: undefined reference to `dwarf_dealloc'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:94: undefined reference to `dwarf_whatattr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:95: undefined reference to `dwarf_get_AT_name'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:101: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::printError(char const*, int, char const*, int, Dwarf_Die_s*, Dwarf_Error_s*)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:111: undefined reference to `dwarf_errmsg'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::getNameAttribute(Dwarf_Die_s*, char const**)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:129: undefined reference to `dwarf_attr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:137: undefined reference to `dwarf_formstring'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:148: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::getTypeAttribute(Dwarf_Die_s*, Dwarf_Die_s**)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:162: undefined reference to `dwarf_attr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:168: undefined reference to `dwarf_global_formref'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:174: undefined reference to `dwarf_offdie'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:183: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::getByteSizeAttribute(Dwarf_Die_s*, unsigned long long*)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:194: undefined reference to `dwarf_attr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:200: undefined reference to `dwarf_formudata'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:209: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::buildType(Dwarf_Die_s*, vmi::VmiType**)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:225: undefined reference to `dwarf_tag'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:231: undefined reference to `dwarf_get_TAG_name'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:397: undefined reference to `dwarf_bytesize'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::buildPrimitiveType(Dwarf_Die_s*, vmi::VmiType**)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:397: undefined reference to `dwarf_bytesize'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::buildPointerType(Dwarf_Die_s*, vmi::VmiType**)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:129: undefined reference to `dwarf_attr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:137: undefined reference to `dwarf_formstring'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:148: undefined reference to `dwarf_dealloc'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:298: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::buildTypedefType(Dwarf_Die_s*, vmi::VmiType**)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:129: undefined reference to `dwarf_attr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:137: undefined reference to `dwarf_formstring'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:148: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::buildArrayType(Dwarf_Die_s*, vmi::VmiType**)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:322: undefined reference to `dwarf_child'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:327: undefined reference to `dwarf_tag'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:332: undefined reference to `dwarf_attr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:357: undefined reference to `dwarf_dealloc'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:359: undefined reference to `dwarf_dealloc'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:338: undefined reference to `dwarf_formudata'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:355: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::buildStructureType(Dwarf_Die_s*, bool, vmi::VmiType**)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:529: undefined reference to `dwarf_child'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:533: undefined reference to `dwarf_dealloc'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:548: undefined reference to `dwarf_siblingof'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:549: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::getMemberOffsetInBytes(Dwarf_Die_s*, unsigned int*)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:419: undefined reference to `dwarf_attr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:426: undefined reference to `dwarf_attr_offset'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:433: undefined reference to `dwarf_loclist'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:459: undefined reference to `dwarf_dealloc'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:456: undefined reference to `dwarf_dealloc'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:457: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::getVariableName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Dwarf_Die_s*)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:129: undefined reference to `dwarf_attr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:137: undefined reference to `dwarf_formstring'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:148: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::processTypes()':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:571: undefined reference to `dwarf_get_pubtypes'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:578: undefined reference to `dwarf_pubtype_name_offsets'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:584: undefined reference to `dwarf_offdie'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:597: undefined reference to `dwarf_pubtypes_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::processFile(Elf*)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:606: undefined reference to `dwarf_elf_init'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:617: undefined reference to `dwarf_set_frame_rule_initial_value'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:618: undefined reference to `dwarf_set_frame_rule_table_size'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:619: undefined reference to `dwarf_set_frame_cfa_value'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:620: undefined reference to `dwarf_set_frame_same_value'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:621: undefined reference to `dwarf_set_frame_undefined_value'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:624: undefined reference to `dwarf_get_address_size'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `~ElfDwarf':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:47: undefined reference to `dwarf_dealloc'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:51: undefined reference to `dwarf_finish'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::printDie(Dwarf_Die_s*)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:71: undefined reference to `dwarf_tag'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:72: undefined reference to `dwarf_get_TAG_name'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::printAttributes(Dwarf_Die_s*)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:87: undefined reference to `dwarf_attrlist'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:99: undefined reference to `dwarf_dealloc'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:94: undefined reference to `dwarf_whatattr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:95: undefined reference to `dwarf_get_AT_name'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:101: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::printError(char const*, int, char const*, int, Dwarf_Die_s*, Dwarf_Error_s*)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:111: undefined reference to `dwarf_errmsg'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::getNameAttribute(Dwarf_Die_s*, char const**)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:129: undefined reference to `dwarf_attr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:137: undefined reference to `dwarf_formstring'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:148: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::getTypeAttribute(Dwarf_Die_s*, Dwarf_Die_s**)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:162: undefined reference to `dwarf_attr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:168: undefined reference to `dwarf_global_formref'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:174: undefined reference to `dwarf_offdie'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:183: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::getByteSizeAttribute(Dwarf_Die_s*, unsigned long long*)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:194: undefined reference to `dwarf_attr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:200: undefined reference to `dwarf_formudata'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:209: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::buildType(Dwarf_Die_s*, vmi::VmiType**)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:225: undefined reference to `dwarf_tag'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:231: undefined reference to `dwarf_get_TAG_name'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:397: undefined reference to `dwarf_bytesize'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::buildPrimitiveType(Dwarf_Die_s*, vmi::VmiType**)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:397: undefined reference to `dwarf_bytesize'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::buildPointerType(Dwarf_Die_s*, vmi::VmiType**)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:129: undefined reference to `dwarf_attr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:137: undefined reference to `dwarf_formstring'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:148: undefined reference to `dwarf_dealloc'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:298: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::buildTypedefType(Dwarf_Die_s*, vmi::VmiType**)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:129: undefined reference to `dwarf_attr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:137: undefined reference to `dwarf_formstring'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:148: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::buildArrayType(Dwarf_Die_s*, vmi::VmiType**)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:322: undefined reference to `dwarf_child'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:327: undefined reference to `dwarf_tag'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:332: undefined reference to `dwarf_attr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:357: undefined reference to `dwarf_dealloc'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:359: undefined reference to `dwarf_dealloc'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:338: undefined reference to `dwarf_formudata'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:355: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::buildStructureType(Dwarf_Die_s*, bool, vmi::VmiType**)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:529: undefined reference to `dwarf_child'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:533: undefined reference to `dwarf_dealloc'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:548: undefined reference to `dwarf_siblingof'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:549: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::getMemberOffsetInBytes(Dwarf_Die_s*, unsigned int*)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:419: undefined reference to `dwarf_attr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:426: undefined reference to `dwarf_attr_offset'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:433: undefined reference to `dwarf_loclist'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:459: undefined reference to `dwarf_dealloc'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:456: undefined reference to `dwarf_dealloc'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:457: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::getVariableName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Dwarf_Die_s*)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:129: undefined reference to `dwarf_attr'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:137: undefined reference to `dwarf_formstring'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:148: undefined reference to `dwarf_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::processTypes()':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:571: undefined reference to `dwarf_get_pubtypes'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:578: undefined reference to `dwarf_pubtype_name_offsets'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:584: undefined reference to `dwarf_offdie'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:597: undefined reference to `dwarf_pubtypes_dealloc'
> /apollo/s2e/build/libvmi-release/src/libvmi.a(ElfDwarf.cpp.o): In function `vmi::ElfDwarf::processFile(Elf*)':
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:606: undefined reference to `dwarf_elf_init'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:617: undefined reference to `dwarf_set_frame_rule_initial_value'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:618: undefined reference to `dwarf_set_frame_rule_table_size'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:619: undefined reference to `dwarf_set_frame_cfa_value'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:620: undefined reference to `dwarf_set_frame_same_value'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:621: undefined reference to `dwarf_set_frame_undefined_value'
> /apollo/s2e/source/s2e/libvmi/src/ElfDwarf.cpp:624: undefined reference to `dwarf_get_address_size'
> clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
> tools/revgen32/CMakeFiles/revgen32.dir/build.make:195: recipe for target 'tools/revgen32/revgen32' failed
> make[3]: *** [tools/revgen32/revgen32] Error 1
> make[3]: Leaving directory '/apollo/s2e/build/tools-release'
> CMakeFiles/Makefile2:556: recipe for target 'tools/revgen32/CMakeFiles/revgen32.dir/all' failed
> make[2]: *** [tools/revgen32/CMakeFiles/revgen32.dir/all] Error 2
> make[2]: *** Waiting for unfinished jobs....
> clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
> tools/revgen64/CMakeFiles/revgen64.dir/build.make:195: recipe for target 'tools/revgen64/revgen64' failed
> make[3]: *** [tools/revgen64/revgen64] Error 1
> make[3]: Leaving directory '/apollo/s2e/build/tools-release'
> CMakeFiles/Makefile2:585: recipe for target 'tools/revgen64/CMakeFiles/revgen64.dir/all' failed
> make[2]: *** [tools/revgen64/CMakeFiles/revgen64.dir/all] Error 2
> make[2]: Leaving directory '/apollo/s2e/build/tools-release'
> Makefile:148: recipe for target 'all' failed
> make[1]: *** [all] Error 2
> make[1]: Leaving directory '/apollo/s2e/build/tools-release'
> /apollo/s2e/source/scripts//..//s2e/Makefile:200: recipe for target 'stamps/tools-release-make' failed
> make: *** [stamps/tools-release-make] Error 2
> make: Leaving directory '/apollo/s2e/build'
> ERROR: [build] 
> 
>   RAN: /usr/bin/make --directory=/apollo/s2e/build --file=/apollo/s2e/source/Makefile install
> 
>   STDOUT:
> 
> 
>   STDERR:
> 

The target revgen64 can be generated successfully. I also checked the lib dwarf is installed via "apt-get install libdward-dev". I was wondering whether I can get any help on this issue. Or if this is hard to solve, is there any possibility that I could skip building 32-bit libraries?

Thanks a  lot!

**Comment by Codefiring** [comment]
Hi there, have you solved this problem ? What OS did you use ?

**Comment by ZiwenWan** [comment]
Thanks for the reply! I tried both Ubuntu 16.04 LTS and 14.04 LTS. The same problem still exists. I was not realized that s2e will build its own version library. Will it check the installed version in my machine and use it by default? I will check the linker invocation and make sure that the lib you mentioned is included.

**Comment by vitalych** [comment]
Could you try with a recent version of Ubuntu? S2E doesn't support older ones, though fixes are welcome.

**Comment by Codefiring** [comment]
Thanks for your reply! It seems have some relavant with the version of gcc. After changing it to gcc-9, the problem doesn't show up again (os: ubuntu 18 & ubuntu 20).

**Comment by sajid36** [comment]
I am having the same issue.
GCC 9.4.0
G++ 9.4.0
Ubuntu 18.04
![Screenshot from 2022-01-20 21-56-36](https://user-images.githubusercontent.com/30213560/150457885-d4da9a60-ee02-481c-9c48-5daa2c696b39.png)

**Comment by vitalych** [comment]
I don't think I will address this for Ubuntu 18.04. I will instead add support for 22.04 LTS and drop 18.04.
