### ISSUE TITLE
Windows development environment provisioning

### ISSUE THREAD

**Issue by jskim20210115** [S2E/s2e-env#439]
Hi, Currently I'm trying to create a windows development environment to support more windows images for S2E in my testing environment.
I'm following the guideline here but it seems http://s2e.systems/docs/WindowsEnvSetup.html the provisioning script https://github.com/S2E/s2e/blob/master/scripts/windows/Setup-DevHost.ps1 is not working properly.

It shows error like this.
```
Unexpected token 'modify' in  expression or statement.
```
![image](https://user-images.githubusercontent.com/82015952/135592229-7648cf8a-81be-46b6-abb6-adc99a51c691.png)

What should I do to make the script working?

FYI, the guest os is windows 1909 updated jun 2021.

Thank you.
Regards,
JS Kim

**Comment by vitalych** [comment]
The visual studio installer has most likely been updated and has different parameters now.
You will need to update the line here accordingly: https://github.com/S2E/s2e/blob/master/scripts/windows/Setup-DevHost.ps1#L16

**Comment by jskim20210115** [comment]
Thanks for the reply.
I'm now trying to retry the script after modifying it like below.
`cd "C:\Program Files (x86)\Microsoft Visual Studio\Installer"
vs_installer.exe modify --installPath 'C:\Program Files (x86)\Microsoft Visual Studio\2019\community' --add Microsoft.VisualStudio.Component.VC.v141.x86.x64.Spectre --add Microsoft.VisualStudio.Component.VC.Runtimes.x86.x64.Spectre --quiet`

It seems the provisioning script is now working.
But still I cannot build the project (windows guest tools) because the build tools for v141_xp cannot be found.

Is it okay to use another version of build tools?

![Screenshot from 2021-10-05 11-35-55](https://user-images.githubusercontent.com/82015952/135951801-68d71945-90d7-430c-a69a-57c3b3733a69.png)

![Screenshot from 2021-10-05 11-38-14](https://user-images.githubusercontent.com/82015952/135951832-5e790cca-e96e-4c90-9255-1a45cfb631a0.png)

**Comment by vitalych** [comment]
You could install v141_xp manually like this: https://stackoverflow.com/questions/49516896/how-to-install-build-tools-for-v141-xp-for-vc-2017
Maybe there is a command line switch for that too.

Upgrading might probably be ok, double-check that the resulting binaries still run in the Windows XP images.

**Comment by jskim20210115** [comment]
Thank you. Let me try it.

**Comment by vitalych** [comment]
@jskim20210115 please check the pull request
