### ISSUE TITLE
qemu: build fails because of deprecated AES function

### ISSUE THREAD

**Issue by Pl0414141** [S2E/s2e-env#442]
's2e build' command on Ubuntu 20.04 TLS clean install report the following error:

In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c: In function ‘aes_encrypt_native’:
/home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:60:5: error: ‘nettle_aes_encrypt’ is deprecated [-Werror=deprecated-declarations]
   60 |     aes_encrypt(&aesctx->enc, length, dst, src);
      |     ^~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:26,
                 from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/usr/include/nettle/aes.h:173:1: note: declared here
  173 | aes_encrypt(const struct aes_ctx *ctx,
      | ^~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c: In function ‘aes_decrypt_native’:
/home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:67:5: error: ‘nettle_aes_decrypt’ is deprecated [-Werror=deprecated-declarations]
   67 |     aes_decrypt(&aesctx->dec, length, dst, src);
      |     ^~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:26,
                 from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/usr/include/nettle/aes.h:177:1: note: declared here
  177 | aes_decrypt(const struct aes_ctx *ctx,
      | ^~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c: In function ‘aes_encrypt_wrapper’:
/home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:134:5: error: ‘nettle_aes_encrypt’ is deprecated [-Werror=deprecated-declarations]
  134 |     aes_encrypt(&aesctx->enc, length, dst, src);
      |     ^~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:26,
                 from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/usr/include/nettle/aes.h:173:1: note: declared here
  173 | aes_encrypt(const struct aes_ctx *ctx,
      | ^~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c: In function ‘aes_decrypt_wrapper’:
/home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:141:5: error: ‘nettle_aes_decrypt’ is deprecated [-Werror=deprecated-declarations]
  141 |     aes_decrypt(&aesctx->dec, length, dst, src);
      |     ^~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:26,
                 from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/usr/include/nettle/aes.h:177:1: note: declared here
  177 | aes_decrypt(const struct aes_ctx *ctx,
      | ^~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c: In function ‘qcrypto_cipher_ctx_new’:
/home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:330:13: error: ‘nettle_aes_set_encrypt_key’ is deprecated [-Werror=deprecated-declarations]
  330 |             aes_set_encrypt_key(&((QCryptoNettleAES *)ctx->ctx)->enc,
      |             ^~~~~~~~~~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:26,
                 from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/usr/include/nettle/aes.h:158:1: note: declared here
  158 | aes_set_encrypt_key(struct aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:332:13: error: ‘nettle_aes_set_decrypt_key’ is deprecated [-Werror=deprecated-declarations]
  332 |             aes_set_decrypt_key(&((QCryptoNettleAES *)ctx->ctx)->dec,
      |             ^~~~~~~~~~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:26,
                 from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/usr/include/nettle/aes.h:163:1: note: declared here
  163 | aes_set_decrypt_key(struct aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:335:13: error: ‘nettle_aes_set_encrypt_key’ is deprecated [-Werror=deprecated-declarations]
  335 |             aes_set_encrypt_key(&((QCryptoNettleAES *)ctx->ctx_tweak)->enc,
      |             ^~~~~~~~~~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:26,
                 from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/usr/include/nettle/aes.h:158:1: note: declared here
  158 | aes_set_encrypt_key(struct aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:337:13: error: ‘nettle_aes_set_decrypt_key’ is deprecated [-Werror=deprecated-declarations]
  337 |             aes_set_decrypt_key(&((QCryptoNettleAES *)ctx->ctx_tweak)->dec,
      |             ^~~~~~~~~~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:26,
                 from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/usr/include/nettle/aes.h:163:1: note: declared here
  163 | aes_set_decrypt_key(struct aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:340:13: error: ‘nettle_aes_set_encrypt_key’ is deprecated [-Werror=deprecated-declarations]
  340 |             aes_set_encrypt_key(&((QCryptoNettleAES *)ctx->ctx)->enc,
      |             ^~~~~~~~~~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:26,
                 from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/usr/include/nettle/aes.h:158:1: note: declared here
  158 | aes_set_encrypt_key(struct aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:342:13: error: ‘nettle_aes_set_decrypt_key’ is deprecated [-Werror=deprecated-declarations]
  342 |             aes_set_decrypt_key(&((QCryptoNettleAES *)ctx->ctx)->dec,
      |             ^~~~~~~~~~~~~~~~~~~
In file included from /home/ubuntu/s2e/source/qemu/crypto/cipher-nettle.c:26,
                 from /home/ubuntu/s2e/source/qemu/crypto/cipher.c:155:
/usr/include/nettle/aes.h:163:1: note: declared here
  163 | aes_set_decrypt_key(struct aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~~~~~
  CC      crypto/tlscredspsk.o
  CC      crypto/tlscredsx509.o
  CC      crypto/tlssession.o
  CC      crypto/secret.o
  CC      crypto/random-gnutls.o
cc1: all warnings being treated as errors
make[1]: *** [/home/ubuntu/s2e/source/qemu/rules.mak:69: crypto/cipher.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/ubuntu/s2e/build/qemu-release'
make: *** [/home/ubuntu/s2e/source/s2e//..//scripts/Makefile.qemu:72: stamps/qemu-release-make] Error 2
make: Leaving directory '/home/ubuntu/s2e/build'
ERROR: [build] 

  RAN: /usr/bin/make --directory=/home/ubuntu/s2e/build --file=/home/ubuntu/s2e/source/Makefile install

  STDOUT:

  STDERR:

**Comment by vitalych** [comment]
This could probably be worked around by disabling cryptography when building qemu.

**Comment by vitalych** [comment]
https://github.com/S2E/qemu/blob/v3.0.0-se/configure#L1354

**Comment by vitalych** [comment]
Did you get a chance to fix it?
