### ISSUE TITLE
Issue with InvokePlugin

### ISSUE THREAD

**Issue by csergi** [S2E/s2e-env#444]
Hi. I was attempting to run a simple test on a malware sample, and I found the following in stderr:

BaseInstructions: ERROR: invokePlugin could not find plugin StaticStateMerger.

I wasn't able to figure out how to actually get the StaticStateMerger plugin. Am I missing something obvious (I included BaseInstructions in the s2e-config.lua)?

**Comment by vitalych** [comment]
I guess you are running Windows guest right? If so the error is benign, you can ignore the message.
