### ISSUE TITLE
Problem:pip install .

### ISSUE THREAD

**Issue by lkpama** [S2E/s2e-env#446]
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 docker.io : Depends: containerd (>= 1.2.6-0ubuntu1~)
E: Unable to correct problems, you have held broken packages.
ERROR: [init] 

  RAN: /usr/bin/sudo -S apt-get install --no-install-recommends build-essential cmake wget git texinfo flex bison python3 python3-dev python3-pip libguestfs-tools genisoimage xz-utils docker.io p7zip-full fuse libhivex-bin jigdo-file libdwarf-dev libelf-dev libelf-dev:i386 libiberty-dev binutils-dev libreadline-dev libboost-dev zlib1g-dev libjemalloc-dev nasm pkg-config libmemcached-dev libvdeplug-dev libpq-dev libc6-dev-i386 libboost-system-dev libboost-serialization-dev libboost-regex-dev libprotobuf-dev protobuf-compiler libbsd-dev libsigc++-2.0-dev libsdl-dev libglib2.0-dev libglib2.0-dev:i386 libglib2.0-0:i386 python-docutils qemu mingw-w64 gcc-multilib g++-multilib libpixman-1-dev libtinfo5 wine-stable lcov jq lib32ncurses5 lib32ncurses5-dev libncurses5-dev libncurses5-dev:i386 libx32ncurses5-dev python-distro pxz

  STDOUT:

  STDERR:

Can you help me？

**Comment by vitalych** [comment]
This looks like an apt-get install issue with your system. Does it work if you install in a clean vm?

**Comment by vitalych** [comment]
No reply, closing
