### ISSUE TITLE
Malware system call

### ISSUE THREAD

**Issue by wjcif11** [S2E/s2e-env#447]
Can I use this tool to record the system call sequence of malware and how to operate it if possible, or do I need to write a plug-in implementation?

**Comment by vitalych** [comment]
Hi, if all you need to trace is system calls / api calls and don't need anything else, it's better to use Cuckoo Sandbox:
https://cuckoosandbox.org/

**Comment by wjcif11** [comment]
> 您好，如果您只需要跟踪系统调用/api 调用并且不需要其他任何东西，最好使用 Cuckoo Sandbox： [https](https://cuckoosandbox.org/) : //cuckoosandbox.org/ 如果需要组合，您可以将其安装在 S2E 来宾中它与其他分析。
Thank you,do you mean that cuckoo sandbox can be installed inside S2E and used together? Is there a tutorial here or do I need to install it myself?

**Comment by vitalych** [comment]
There is no tutorial. In principle, cuckoo can be installed on any windows machine, so also in the S2E guest. I would recommend you install it on a normal VM first, without S2E. Once you know how it works and the results are what you need, you can look into integrating it into S2E.
