### ISSUE TITLE
How to make network data symbolic?

### ISSUE THREAD

**Issue by AminoACID123** [S2E/s2e-env#450]
Hi, I want to test a web server that accepts data from socket. Is it possible to make the data symbolic?

**Comment by vitalych** [comment]
You can intercept with read syscalls with LD_PRELOAD and inject symbolic data in the buffer. You can extend libs2e.so for that. 
There are more explanations on the forum. Please post there if you have more questions of general interest.
https://groups.google.com/g/s2e-dev/search?q=socket

**Comment by AminoACID123** [comment]
Thanks for the quick reply. I will look into it. Closing this issue for now.
