### ISSUE TITLE
Remove pygit2 dependency

### ISSUE THREAD

**Issue by ameily** [S2E/s2e-env#455]
We are trying to get s2e-env installed on Ubuntu 20.04, the latest LTS release. We've run into a version conflict on pygit2, which is pinned to 1.2.1, and requires libgit2 v1.0.X. Ubuntu's libgit2-dev package is v0.28, which is incompatible and pygit2 fails to build.

Doing a quick search, it looks like pygit2 is only used in s2e-env to [get the user name when creating a plugin](https://github.com/S2E/s2e-env/blob/master/s2e_env/commands/new_plugin.py#L65). I purpose that this code changes slightly:

- Add an optional `--author-name` parameter
- If `--author-name` isn't provided, use the current user name, via something like [`getpass.getuser()`](https://docs.python.org/3/library/getpass.html#getpass.getuser)
- Remove the pygit2 dependency

If this issue is approved, I should be able to handle the PR since I think it's straightforward.

**Comment by vitalych** [comment]
How about unpinning the version?

**Comment by ameily** [comment]
Unpinning the pygit2 version may work, but it looks like it was originally pinned to resolve a docker build issue: cbb82e40beb6178e624164f24dcf5ff3786436c9.

I think either solution would work for my situation.

**Comment by vitalych** [comment]
got it, let's remove the dependency then.

**Comment by ameily** [comment]
Sounds good, I should have a PR up later today.
