### ISSUE TITLE
libs2e-release-make target is not valid

### ISSUE THREAD

**Issue by ameily** [S2E/s2e-env#457]
I am developing an S2E plugin and want to rebuild just the plugin after I make a modification. I found a previous issue, #120, that says the `libs2e-release-make` target can be used to significantly speed up plugin builds. However, it looks like that target doesn't exist:

```
$ s2e build -r libs2e-release-make
ERROR: [build] Component libs2e-release-make is not valid. Valid components are: qemu

$ make -f s2e/source/Makefile list
all-debug all-release qemu-debug qemu-release stamps/qemu-debug-install stamps/qemu-debug-make stamps/qemu-release-install stamps/qemu-release-make
```

The `Valid compoents are: qemu` is also interesting since, based on #69, I think it should print out all the targets.

Is there a better target I should be using after I make a change to a single plugin that I am developing?

**Comment by vitalych** [comment]
The build command needs fixing to list targets properly. You will need to build libs2e-release manually like this:

```
(venv) ~/s2e/env/build$ S2E_PREFIX=/home/user/s2e/env/install/ make -f ../source/s2e/Makefile stamps/libs2e-release-install
```

See the Makefile for other targets.
