### ISSUE TITLE
Image download is broken

### ISSUE THREAD

**Issue by michaelbrownuc** [S2E/s2e-env#458]
Downloading images via the `s2e image_build` command no longer works. The issue is rooted in `utils.google.py`. Google Drive no longer sends tokens to confirm downloads that cannot be scanned. Looking at the request in a browser, it appears now a variable should be sent with the GET request instead : `confirm=t`.

**Comment by michaelbrownuc** [comment]
Have a fix ready, can submit a PR.

**Comment by vitalych** [comment]
Thanks! I'd be happy to try it out.
