### ISSUE TITLE
AMD Epyc support

### ISSUE THREAD

**Issue by Pl0414141** [S2E/s2e-env#463]
Hi,

I was wondering if there are any limitations or restrictions with using AMD Epyc/Threadripper processors instead of Intel for S2E use? Does S2E make use of any Intel-only features?

Thank you

**Comment by vitalych** [comment]
S2E should run on any x86 host, I run it on a Threadripper.
The guest however sees some QEMU flavor of an x86-compatible CPU. The emulation engine is inherited from QEMU 1.0, so the instruction set that guests can use is fairly limited.
