### ISSUE TITLE
Cannot create new new project in Ubuntu 22.04

### ISSUE THREAD

**Issue by michaelbrownuc** [S2E/s2e-env#467]
Hello,

Thanks for updating S2E to the latest LTS. I was unable to create a new project in S2E env after building using Python 3.10 due to an issue in the forked version of pyelftools. In 

https://github.com/S2E/pyelftools/blob/master/elftools/construct/lib/container.py#L5

An API change causes a runtime failure.

This line should be:

`from collections.abc import MutableMapping`

I've made the change locally and confirmed it resolves the issue with project creation.

Thanks!

**Comment by michaelbrownuc** [comment]
Please note that I've marked the issue here as issues are disabled on the `pyelftools` fork for S2E

**Comment by vitalych** [comment]
Hi! please send pull requests for such bugs directly, thanks!

s2e-env is the right place for all issues.

**Comment by vitalych** [comment]
It would be good to update pyelftools to the upstream version, then reapply s2e-specific commits on top, if they are still relevant.

**Comment by vitalych** [comment]
Finally, I'd like to know how to reproduce this. `s2e new_project` works fine for me.

**Comment by michaelbrownuc** [comment]
https://github.com/S2E/pyelftools/pull/2

**Comment by michaelbrownuc** [comment]
> Finally, I'd like to know how to reproduce this. `s2e new_project` works fine for me.

This occurs for me on a fresh install of Ubuntu 22.04 using Python 3.10.4 as the Python version.

**Comment by michaelbrownuc** [comment]
New PR (still a draft), for reference:

https://github.com/S2E/pyelftools/pull/3

**Comment by michaelbrownuc** [comment]
I've finished testing related to #469 and haven't seen any issues using the updated `pyelftools`. We should be ok to tackle this now
