### ISSUE TITLE
Run Background Process within Analysis VM

### ISSUE THREAD

**Issue by ameily** [S2E/s2e-env#470]
I'm trying to use S2E to trace a simple socket server. To test, I copy a client binary into the qemu analysis image and modify `bootstrap.sh` to run the client in the background after a 5 second delay alongside the server.

```bash
##### run-client.sh #####
#!/bin/bash
echo waiting 10 seconds for server to start
sleep 10s
echo client waking up
./client

##### bootstrap.sh #####
# before call to execute()
set -m  # enable bash job control
./run-client.sh &
```

I'm seeing that the call to `sleep` seems to never exit on most runs and, when this happens, the trace locks up and I never see the "client waking up" message in `serial.txt`.

Is running a background task, such as a socket client, supported in S2E or am I doing something wrong?

**Comment by ameily** [comment]
I apologize, I'm thinking that the export may have missed some custom functionality that my environment has. Thanks for the guidance on `GUI=1`! Here is what I am seeing:

<img width="881" alt="image" src="https://user-images.githubusercontent.com/749571/174895504-fd2b3857-892e-4f75-b628-dd3810ede0f3.png">

It appears to still lock up waiting for the client to run, which it never does. I've confirmed that this works occasionally.

**Comment by vitalych** [comment]
Perhaps you could check with gdb why it gets stuck (it's installed in the guest).

**Comment by vitalych** [comment]
When sleep is stuck, can you still interrupt the script with ctrl+c? I think at some point I got in a state where ctrl+c wasn't working for some reason.

**Comment by ameily** [comment]
> I think at some point I got in a state where ctrl+c wasn't working for some reason.

I'm seeing this as well. Once sleep is stuck, I cannot ctrl+c the image and I have to kill the qemu process.

**Comment by vitalych** [comment]
Could you try to login into a different console then check:
- if there are kernel exceptions in dmesg (e.g., cpu stuck message)
- if timer interrupts are generated (date is advancing and counters in `cat /proc/interrupts` are incremented)

Put qemu in fullscreen (ctrl+alt+f), then switch to another console (ctrl+alt+f1), login (s2e:s2e), interrupt the login script to get to the terminal.

**Comment by ameily** [comment]
It looks like the entire VM is locked up because I am unable to switch consoles when this occurs. However, the lock up appears to not happen if I switch to another console prior to `sleep` running.

**Comment by vitalych** [comment]
Could you do the following:
- remove `--monitor null` from launch.sh,
- start qemu
- when it gets stuck, open the console with ctrl+alt+2
- Run `(qemu) info registers`
- Save the output.
I'd like to see if the interrupt flag is set.

Also, does it work if you try with a debug build? 
- `s2e build -g`.
- ./launch-s2e.sh debug

I could also try to debug remotely.

**Comment by ameily** [comment]
`info registers` hangs as well:

<img width="438" alt="image" src="https://user-images.githubusercontent.com/749571/175382650-53414244-3e0d-4035-ba10-7f015d65f7a6.png">

I'm rebuilding in debug mode now.

**Comment by vitalych** [comment]
This is good, it is much easier to debug qemu than the guest.

**Comment by ameily** [comment]
I built S2E in debug mode but I'm unable to launch the Qemu image. It looks like the libs2e.so file doesn't exist:

```
$ ./launch-s2e.sh
ERROR: ld.so: object '/home/user/Projects/s2e-debug/s2e/install/share/libs2e/libs2e-i386-s2e.so'
from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Could not access KVM kernel module: No such file or directory
qemu-system-i386: failed to initialize KVM: No such file or directory
```

The `s2e/install/share/libs2e` directory does not exist. I tried to find the SO it's looking for and I'm not seeing it in install or build. I've confirmed that the release build of `launch-s2e.sh` is still working.

**Comment by ameily** [comment]
Great, thanks! I ran into two more issues trying to get `launch-s2e.sh` to run. Let me know if I did something wrong or if these should be a new issue/PR:

- In `launch-s2e.sh`: the path to the shared directory doesn't exist and qemu failed to start becuase it is attempting to load `$S2E_SHARED_DIR/op_helper.bc.i386`. I fixed this locally by adjusting the shared dir while in debug mode:
  ```
  # the original line, keep as-is
  export S2E_SHARED_DIR=$INSTALL_DIR/share/libs2e

  # later... in the "debug" if block
  export S2E_SHARED_DIR="$BUILD_DIR/libs2e-$BUILD/i386-$S2E_MODE-softmmu"
  ```

- The link to `guest-tools32` was broken and pointed to a directory that didn't exist (`$INSTAL_DIR/bin/guest-tools32`). I updated the link to point to the release directory.

With that, gdb runs but the sample crashes early on:

```
[Z3] Initializing
1 [State 0] Created initial state
Initializing periodic timer
qemu-system-i386: /home/meilya/Projects/brp-s2e-debug/s2e/build/llvm-14.0.0.src/include/llvm/IR/Type.h:379:
  llvm::Type *llvm::Type::getNonOpaquePointerElementType() const:
    Assertion `getTypeID() == PointerTyID' failed.
```

Here's the full backtrace: [S2E-GDB-StackTrace.txt](https://github.com/S2E/s2e-env/files/8976768/S2E-GDB-StackTrace.txt)

**Comment by vitalych** [comment]
It looks like the scripts assume that the release build is present as well

**Comment by ameily** [comment]
That's what I figured. I'm building S2E in release mode alongside debug now to see if that resolves the issues.

**Comment by vitalych** [comment]
I have the same crash.

**Comment by vitalych** [comment]
Here is the fix, let me know if it works: https://github.com/S2E/s2e/pull/59

**Comment by ameily** [comment]
The patch in https://github.com/S2E/s2e/pull/59 worked.

I was able to trigger the behavior and then pull the stacktrace and register info. I hope this helps: [Debug-Lockup-GDB.txt](https://github.com/S2E/s2e-env/files/8984831/Debug-Lockup-GDB.txt)

**Comment by vitalych** [comment]
Could you please dump the stack for all threads?

**Comment by ameily** [comment]
here's the stack trace and register output for every thread when the VM freezes, including on the `info registers` from the qemu console. I notice that one thread is in a custom plugin we are developing, which I'll investigate locally to see if there is something wrong there. Could a misbehaving plugin cause something like this?

[Debug-Lockup-GDB.txt](https://github.com/S2E/s2e-env/files/8987028/Debug-Lockup-GDB.txt)

**Comment by vitalych** [comment]
Ah yes. You should not do any complex tasks on the critical path (i.e., when a translation block is executing). It would block qemu, which processes some I/O events when the CPU loop is idle. In this case, `info registers` gets stuck waiting for the CPU to be freed, it's occupied by your plugin code.

**Comment by vitalych** [comment]
Did you resolve it?

**Comment by ameily** [comment]
It appears to be an issue within a plugin I am working. I really appreciate all your help troubleshooting and for fixing the debug build issue in https://github.com/S2E/s2e/pull/59. I believe this issue can be closed now.
