### ISSUE TITLE
Generate input for code coverage

### ISSUE THREAD

**Issue by GATT0** [S2E/s2e-env#477]

**Comment by vitalych** [comment]
When closing an issue, please explain how you solved it. Also don't delete the description.

**Comment by GATT0** [comment]
I solved the issue simply by looking at the documentation, I found out that I was creating all of my projects with the wrong flags so that they couldn't generate any input for code coverage.
I decided to delete the description because it was all documented and I thought nobody would need the solution.
Sorry for the inconvenience.
Yours sincerely.
