### ISSUE TITLE
Reached max crash count limit

### ISSUE THREAD

**Issue by GATT0** [S2E/s2e-env#480]
Hi, 
I'm generating PoVs for some applications, in particular I'm generating inputs that make the program crash, but every time S2E generate 6 inputs it stops and in the [debug file](https://github.com/S2E/s2e-env/files/9640661/debug.txt) I found this:
PovGenerationPolicy: Reached max crash count limit.
So I found the PovGenerationPolicy.cpp file in the plugins folder and I tried to modify it by incrementing the number of crashes it can generate, but nothing changed.
Thank for your time.
Yours sincerely.

**Comment by vitalych** [comment]
Can you set this value in s2e-config.lua instead?

**Comment by GATT0** [comment]
Thank you, it worked. In the s2e-config.lua file there was no configuration for this plugin, I just found:  
add_plugin("PovGenerationPolicy").
So I added the body:
pluginsConfig.PovGenerationPolicy = {
	maxCrashCount = 100
}.
Is there a way to configure this plugin when creating the project?

**Comment by vitalych** [comment]
No, you need to edit the config file.

**Comment by GATT0** [comment]
Thanks for your time, I really appreciated it.
Best regards.
