### ISSUE TITLE
s2e image_build debian-11.3-i386 -n

### ISSUE THREAD

**Issue by YaoLianda** [S2E/s2e-env#486]
vmare execute the command:s2e image_build debian-11.3-i386 -n

INFO: [image_build] The following images will be built:
INFO: [image_build]  * debian-11.3-i386
INFO: [sh.command] <Command '/usr/bin/touch /home/yld/s2e/images/.cowcheck', pid 4065>: process started
INFO: [sh.command] <Command '/usr/bin/cp --reflink=always /home/yld/s2e/images/.cowcheck /home/yld/s2e/images/.cowcheck1', pid 4070>: process started
WARNING: [image_build] 
Copy-on-write check failed.
The file system where images are stored (/home/yld/s2e/images) does not support copy-on-write.
It is recommended to use an XFS or BTRFS file system with copy-on-write enabled as a storage
location for S2E images, as this can save up to 60% of disk space. The building process checkpoints
intermediate build steps with cp --reflink=auto to make use of copy-on-write if it is available.

How to upgrade:
    1. Create an XFS or BTRFS partition large enough to store the images that you need (~300 GB for all images).
       Make sure you use reflink=1 to enable copy-on-write when running mkfs.xfs.
    2. Create a directory for guest images on that partition (e.g., /mnt/disk1/images)
    3. Delete the "images" folder in your S2E environment
    4. Create in your S2E environment a symbolic link called "images" to the directory you created in step 2

INFO: [sh.command] <Command '/usr/bin/rm -f /home/yld/s2e/images/.cowcheck', pid 4075>: process started
INFO: [sh.command] <Command '/usr/bin/rm -f /home/yld/s2e/images/.cowcheck1', pid 4080>: process started
INFO: [image_build] Kernel repository already exists in /home/yld/s2e/source/s2e-linux-kernel
/home/yld/s2e/source/s2e-env/venv/lib/python3.10/site-packages/pyftpdlib/authorizers.py:243: RuntimeWarning: write permissions assigned to anonymous user.
  warnings.warn("write permissions assigned to anonymous user.",
INFO: [pyftpdlib] concurrency model: async
INFO: [pyftpdlib] masquerade (NAT) address: 10.0.2.2
INFO: [pyftpdlib] passive ports: None
INFO: [pyftpdlib] >>> starting FTP server on 127.0.0.1:15468, pid=4064 <<<
WARNING: [image_build] Image creation will run in headless mode. Use --gui to see graphic output for debugging
WARNING: [image_build] Image build without KVM. This will be slow
make: Entering directory '/home/yld/s2e/images'
/home/yld/s2e/source/guest-images/Makefile:68: *** You must be member of the docker group to build images.  Stop.
make: Leaving directory '/home/yld/s2e/images'
ERROR: [image_build] 

  RAN: /usr/bin/make --file=/home/yld/s2e/source/guest-images/Makefile --directory=/home/yld/s2e/images -j 2 -r --warn-undefined-variables debian-11.3-i386

  STDOUT:

  STDERR:

What is the reason for this

**Comment by vitalych** [comment]
** You must be member of the docker group to build images. Stop.

**Comment by YaoLianda** [comment]
> 
I have joined the docker group
It's the same question

**Comment by vitalych** [comment]
You need to log out for the groups to be updated.

**Comment by YaoLianda** [comment]
Thank you. The problem has been solved.but I encountered new problems as shown below
Z3] Initializing
1 [State 0] Created initial state
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.40000001H:EAX.kvm-nopiodelay [bit 1]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.40000001H:EAX.kvmclock [bit 3]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.40000001H:EAX.kvm-asyncpf [bit 4]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.40000001H:EAX.kvm-steal-time [bit 5]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.40000001H:EAX.kvm-pv-eoi [bit 6]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.40000001H:EAX.kvmclock-stable-bit [bit 24]
Adding CPU (addr = 0x7fb81000a760, size = 0x36ea0)
qemu-system-x86_64: warning: hub 0 is not connected to host network
Modification timestamp of 'json:{"driver": "s2e"}' changed since the creation of the snapshot 'ready' (st_mtime 1669361554 != 1658661755).
Please recreate a new snapshot.
qemu-system-x86_64: Could not load snapshot 'ready' on 'ide0-hd0': Failed to load snapshot: Operation not permitted

**Comment by vitalych** [comment]
Something has changed the time stamp of the base image, which causes the snapshot to be invalidated. I can't tell why this happens, perhaps your user account is on some network share or shared drive?
