### ISSUE TITLE
Linux image builld fails due to outdated debian

### ISSUE THREAD

**Issue by SoptikHa2** [S2E/s2e-env#495]
I'm not sure how exactly does image build work yet, but it's currently not possible to build any linux image.

It seems that the build script is using debian 9 inside docker in order to build the image. However, debian 9 is unsupported.

> Debian 9 has been superseded by Debian 10 ("buster"). Security updates have been discontinued as of July 6th, 2020. Stretch also had benefited from Long Term Support (LTS) until the end of June 2022.

Debian also killed software repositories for debian 9 and moved them to the archive. This makes the build script fail, since it's impossible to build anything.

One of the following would fix the issue:

- Modify the build docker image to use debian >=10
- Modify the build docker image to use archive as software repository
- Distribute prebuilt version of the docker image.

I think I might find some time to try and fix this later next week, however if anyonce could point me in the right direction, it could save quite a bit of time.

Thank you

**Comment by vitalych** [comment]
Sounds good, please go ahead.
Docker files are in https://github.com/S2E/guest-images/tree/master/Linux/docker
The kernel versions that S2E comes with are a bit old, hopefully it will still work.

**Comment by liheji** [comment]
A temporary solution
Try adding the following to your Dockerfile.x86_64

RUN cp /etc/apt/sources.list /etc/apt/sources.list.backup
RUN echo "deb http://archive.debian.org/debian/ stretch main contrib non-free" > /etc/apt/sources.list
RUN echo "deb-src http://archive.debian.org/debian/ stretch main contrib non-free" >> /etc/apt/sources.list

**Comment by vitalych** [comment]
Thanks, I'll look into it. Just upgrading the image version won't work because then the kernel won't build. We need to upgrade it to something more recent.
