### ISSUE TITLE
CROMU_00001 testing

### ISSUE THREAD

**Issue by jakkdu** [S2E/s2e-env#57]
Hi, I want to test s2e with other CGC binary, CROMU_00001.
I used the s2e docker image, and use /demo/run.sh to create a new project for the CROMU_00001.

But it gives me a lot of warnings and error.
I attached my [debug.txt](https://github.com/S2E/s2e-env/files/1433080/debug.txt).
Do you have any idea what the problem is?

Also, if I want to add a seed file, do I have to just put it to the seeds folder?
In that case, should I use XML format or just binary?

Thanks.

**Comment by vitalych** [comment]
Thanks for the report. There seems to be an error at the end indeed.
As for seeds, they have to be in binary format.

**Comment by vitalych** [comment]
The error seems to be caused by KVM_NMI call from QEMU that libs2e doesn't implement yet. We'll look into it.
As for the seeds, you need to use the binary ones.

**Comment by vitalych** [comment]
Please try https://github.com/S2E/libs2e/pull/8 and let me know if it works.

**Comment by jakkdu** [comment]
Thanks. I tested I didn't get the error.

I think it's not right place, but what does the completed seed mean? 
I put only a single seed, but "completed seeds" keep increasing. 

Also, how can I get testcases? like klee-test?

**Comment by vitalych** [comment]
Test cases are generated automatically when a crash/vulnerability is found. You can find them in the s2e-last folder (*.xml, *.c files).

Completed seed means that the guest fetched the seed and finished executing it. Not sure why it increases only with one seed. Logs would be helpful.

I've also noticed this msg in serial.txt, probably a bug.
./bootstrap.sh: line 147: cb-test: command not found

**Comment by jakkdu** [comment]
I didn't take a look demo.sh carefully, but the docker file does not have cb-test in default path.
I put the [0-0.pov.txt](https://github.com/S2E/s2e-env/files/1441502/0-0.pov.txt) (without .txt) in the seeds directory.
Since debug file is too large, I attach only last 10000 lines, [debug-partial.txt](https://github.com/S2E/s2e-env/files/1441507/debug-partial.txt).
I hope it will be helpful.

What I am trying to do is to create [driller](https://github.com/shellphish/driller) like testcases generation using s2e.
Is there any way to get testcases, not crash, to help fuzzers?

**Comment by vitalych** [comment]
Normal test cases that produce new coverage are generated automatically. You can find them in s2e-last. They have a different prefix than the crash/pov ones.

**Comment by jakkdu** [comment]
Sorry for keep asking.
If you have a reference, then just let me know.
In my s2e-last, it contains a lot of calls*-json, and tb-coverage*.json and 
kill-pov-unknown, and partial-pov-unknown.

What are those files? and what are the testcases?

**Comment by jakkdu** [comment]
Sorry for keep asking.
If you have a reference, then just let me know.
In my s2e-last, it contains a lot of calls*-json, and tb-coverage*.json and 
kill-pov-unknown, and partial-pov-unknown.

What are those files? and what are the testcases?

**Comment by vitalych** [comment]
I will close it for now, as issues have been solved or filed as appropriate
