### ISSUE TITLE
Debian 8.7.1 i386 image build failed (jigdo jigdo jigdo)

### ISSUE THREAD

**Issue by gkso** [S2E/s2e-env#73]
Recent I'm trying to rebuild S2E from scratch using s2e-env, while I was building the Debian 8.7.1 guest image, I encountered the following error:

INFO: [image_build] The following images will be built:
INFO: [image_build]  * debian-8.7.1-i386
INFO: [image_build] Kernel repository already exists in /home/alan/s2e-work/s2e/source/s2e-linux-kernel
WARNING: [image_build] Image creation will run in headless mode. Use --gui to see graphic output for debugging.
make: Entering directory `/home/alan/s2e-work/s2e/images'
[Fri Dec 15 14:52:28 PST 2017] [/home/alan/s2e-work/s2e/images/.tmp-output/debian-8.7.1-i386/debian-8.7.1-i386.iso] Downloading disk image...
wget --no-use-server-timestamps -O /home/alan/s2e-work/s2e/images/.tmp-output/debian-8.7.1-i386/debian-8.7.1-i386.iso https://cdimage.debian.org/mirror/cdimage/archive/8.7.1/i386/iso-cd/debian-8.7.1-i386-netinst.iso
--2017-12-15 14:52:28--  https://cdimage.debian.org/mirror/cdimage/archive/8.7.1/i386/iso-cd/debian-8.7.1-i386-netinst.iso
Resolving cdimage.debian.org (cdimage.debian.org)... 194.71.11.173, 194.71.11.165, 2001:6b0:19::173, ...
Connecting to cdimage.debian.org (cdimage.debian.org)|194.71.11.173|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-12-15 14:52:29 ERROR 404: Not Found.

make: *** [/home/alan/s2e-work/s2e/images/.tmp-output/debian-8.7.1-i386/debian-8.7.1-i386.iso] Error 8
make: Leaving directory `/home/alan/s2e-work/s2e/images'
ERROR: [image_build] 

  RAN: /usr/bin/make --directory=/home/alan/s2e-work/s2e/images --file=/home/alan/s2e-work/s2e/source/guest-images/Makefile -j 2 debian-8.7.1-i386

  STDOUT:

  STDERR:

After some investigation, I found Debian has removed the archived ISO images from its website, and using jigdo files instead. Currently I have to manually download the image. But it would be perfect if s2e-env can automatically do it.

**Comment by vitalych** [comment]
Yes, support will come soon

**Comment by vitalych** [comment]
@gkso please check that this PR works for you

**Comment by gkso** [comment]
Thanks for the very fast response!
