### ISSUE TITLE
Dump incremental coverage data

### ISSUE THREAD

**Issue by vitalych** [S2E/s2e-env#94]
For now coverage is written at state termination, which may be suboptimal if S2E is killed before the paths terminate.

**Comment by adrianherrera** [comment]
Isn't this covered by https://github.com/S2E/libs2eplugins/pull/8?

**Comment by vitalych** [comment]
I forgot that we have this feature...
Actually, that's probably what is needed. I'll check how it works and close/change this issue if needed.

**Comment by vitalych** [comment]
It should be good enough for now, but that functionality is still incomplete. It won't dump all coverage, just coverage of whatever state that is currently running.
